cfpb/hmda-frontend

- src/tools/file-format-verification/actions/index.js
- src/tools/file-format-verification/components/FilingPeriodSelector.jsx
- src/tools/file-format-verification/components/ParseErrors.css
- src/tools/file-format-verification/components/ParseErrors.jsx
- src/tools/file-format-verification/reducers/index.js
Closes #22 
- Updates expected return format for FFVT API
- Updates UI to better align with errors shown in Filing app
- Add 2019 as a drop-down option and as the default period
1. Manual - Multiple errors on LAR row
2. Manual - TS & LAR errors
> Update FFVT API return format

- src/common/configUtils.js
- src/common/constants/config.js
- src/common/useEnvironmentConfig.jsx
Closes #44 
- Uses the `config.json` which I snuck into master instead of the smaller default made in the former `config.js`
1. Load the homepage and note that the announcement text is immediately available.
2. Change the announcement text for dev in `config.json` to something else and reload the page.
3. Note how it will use the default but then pull in the github version when available
For some reason we haven't really been importing json files directly, instead opting to make json-like JS files and importing those. I believe I had some performance concerns for our large json files, but that's pretty much irrelevant for this small stuff (for large files, I wanted to make sure we were shipping a json string that gets `JSON.parsed()` at runtime, because parsing JSON is considerably faster …
> Config in frontend repo

- nginx/nginx.conf
Keycloak uses frames to reauthorize its JWT, it requires 'self' in the frame-src
Closes #59
Closes #60
> add self to csp

- src/filing/index.js
Filing app was crashing when clicking into the Submission page due to missing config.
closes #62
> Pass config to all <AppContainer>

- src/common/constants/config.json
This PR will be used to test updating the Env. config after tonight's initial prod-beta deployment.
Closes #58
- Update homepage announcement
- Update Documentation's default year
1. Prior to merging
- Homepage announcement should begin 'On September...'
- Clicking the `Documentation` link in the header should default to 2018 documentation
2. After merging
- Homepage announcement should begin 'HMDA Filing...'
- Clicking the `Documentation` link in the header should default to 2019 documentation
> Update announcement and default documentation year

- src/filing/actions/fetchLatestSubmission.js
- src/filing/institutions/index.jsx
Companion to #56, fixes a display bug when a filing has no submissions
> Swallow 404 when received for submissions when none exist

- src/filing/actions/handleFile.js
- src/filing/modals/confirmationModal/container.jsx
- src/filing/utils/checkFileErrors.js
Closes https://github.com/cfpb/hmda-platform-ui/issues/1249
Reads the first two bytes of the file, which (in a valid hmda file) will always be '1|'. Displays a unique error message when the file is `.txt` but this invariant is violated.
> Read file bytes

- src/filing/actions/fetchNewFiling.js
- src/filing/reducers/latestSubmissions.js
Closes #76 
- Avoid overwriting latestSubmissions in reducer when dealing with multiple institutions
- Fix action format for creating dummy submission after creating a new filing
> Fix 'Loading' institutions without failed network calls.

- src/common/constants/links.js
- src/homepage/index.js
Without slash, logged-out users are redirected to Auth instead of Filing landing page
> Filing links need ending slash

- src/filing/submission/parseErrors/index.jsx
Closes #83 
- Remove use of `entries()` method, which is not supported by IE.
This was a change already implemented in `hmda-platform-ui` but just got missed in the transition.
> Replace use of Object.entries()

- package.json
- src/filing/modals/confirmationModal/container.jsx
- src/filing/submission/router.jsx
- yarn.lock
Closes #90 
Cleans up some router code and specifically blocks rendering router children on the submission page if the code isn't right.
Somewhat more idiomatic version of https://github.com/cfpb/hmda-frontend/pull/93 which will also prevent users from incorrectly getting to macro/submission page if they've unchecked the verification checkbox.
> Router cleanup and specifically render loader on submission page

- src/common/constants/config.json
Closes #50 
- Updated Homepage announcement text
- Added 2019 as default filing period
- Added 2019 as an available filing period
1. Comment `src/common/useEnvironmentConfig.jsx` line 8 to test locally
2. Verify that Homepage show correct message
3. Click over to Filing
4. Verify that 2019 is available and selected by default.
> [Dec 31] Open and announce 2019 filing season

- src/tools/index.css
Closes #98 
Print preview in Chrome
Print preview in Safari
> Tools: Set print styles to full width

- src/filing/refileWarning/index.jsx
- Adds links to documentation and hmda help to the end of all refile banners:
> Add helpful links to refilewarning banner

- src/data-publication/reports/SearchList.jsx
- src/documentation/markdown/2019/filing-faq.md
- src/documentation/markdown/2020/filing-faq.md
Closes https://github.com/cfpb/hmda-frontend/issues/139
Note that there is still an `ffiec-api` reference in the codebase, namely to `https://ffiec-api.cfpb.gov/public/filers/2017/${institutionId}/msaMds`, which we'll need an alternate solution for.
> swap filers api and remove unneeded ffiec-* references from docs

- src/tools/lar-formatting/AppIntro.jsx
Closes #149 
Currently the link to the larft documentation is speculative and 404s (since it still needs to be created in #137).
> Updates LARFT text

- src/data-publication/reports/Results.css
- src/data-publication/reports/Results.jsx
- src/data-publication/reports/SearchList.css
Closes #167 
- S3 files have been updated as required
- Latest commit enables download for 2017 as well
- Added checkbox for inclusion of header row (2017 & 2018)
- Removed orphaned Sass variable references
> Enable download of mLAR with header row

- src/data-browser/charts/MapContainer.jsx
Closes #164 
Also, addresses some of the bugs brought up in #177 (specifically, showing the percent encoded labels and only showing ids for loan type/purpose, which were regressions)
> Feature layer update

- nginx/nginx.conf
Closes #186 
Not sure if this is the right change as things work fine on the dev server and when built and served locally.  I think I would need to test this in Docker to check locally?
But, based on the CSP for other file types, I think this should fix the image issue.
`img-src 'self' blob: data: https://www.google-analytics.com https://raw.githubusercontent.com;`
> Add github to image CSP

- src/common/constants/config.json
Closes #203 
Add configuration for testing of Quarterly filing in Beta environments.  
- Creates the `filingQuartersLate` entries (Late Quarterly filing dates)
- Updates `filingQuarters` dates to only include the "timely" filing dates.
Note: This will not open any new filingPeriods in `prod` or `prod-beta`, it simply sets up some supporting information ahead of time.  And is needed to continue testing in `dev-beta`...
> Update beta configs with new filing dates

- src/tools/file-format-verification/actions/index.js
Closes #199 
Used `includes` which is not supported by IE.
> Remove method not supported by IE

- Dockerfile
- package.json
Node v8 has been EOL'd, so this switches us to the latest LTS version of node
> Depend on node 12

- src/data-publication/reports/ModifiedLar.jsx
- src/data-publication/reports/Results.jsx
- src/data-publication/reports/SearchList.jsx
Closes #243 
Shows 'Include File Header' option only for mLAR.
> Disclosure Reports: hide Include File Header option

- src/documentation/tools/FFVT.jsx
- src/documentation/tools/LARFT.jsx
Clarifies that the links are to instructions rather than the tools themselves
> Add 'Instructions' to LARFT and FFVT doc sections

- src/data-browser/charts/MapContainer.jsx
Closes #251 
If a browser doesn't support WebGL, we can't do anything other than inform the user. This does so via a handy error message if the map fails to initialize.
> Handle buggy browsers without webgl support

- src/common/constants/config.json
- Remove "Filing season is open." from homepage announcement.
> Update announcement, filing season is not open

- src/data-browser/Home.jsx
Assists with #277, but the real fix there is in Kubernetes.
We should prefer in-app `Link`s where they make sense, since they are lower overhead once the user has already loaded the main bundle.
> Change the faq link to be an in-app link rather than an anchor

- src/App.jsx
- src/MaintenanceMessage.css
- src/MaintenanceMessage.jsx
- src/common/Footer.css
- src/common/Footer.jsx
- src/filing/App.jsx
- src/filing/common/Footer.css
- src/filing/common/Footer.jsx
- src/filing/home/Home.css
- src/filing/home/index.jsx
- src/filing/index.js
Closes #263 
- Adds a persistent Maintenance message banner to the bottom of pages when `maintenanceMode` is enabled.
- Banner is only dismissible on mobile devices (per team feedback). 
- Banner reflects the same maintenance message used for the homepage/filing app 
1. Set `maintenanceMode: true` in config.json for the `dev` environment
2. Maintenance banner will reflect the announcement message and be colored to match the announcement type.
> Maintenance Message bottom banner

- src/common/constants/config.json
Closes #307 
Some small formatting changes.
Only material change is adding "2020" to the `dev-beta` config.
> Open 2020 annual in dev-beta

- src/filing/submission/edits/Table.css
- src/filing/submission/edits/Table.jsx
- src/filing/submission/edits/TableRow.jsx
Closes #262
Closes #291
- Displays appropriate column label for Edit row identifiers (LEI for TS, ULI for LAR)
- Highlights the "Provided" value when it does not match the expected value (S303 only)
- Removes the row identifier column for S303 (previously ULI, but should be LEI since it is a TS edit) because there is another column labeled LEI, used to show the Provided/Expected values.
**S303**: Special case that suppresses the row identifier, highlights Prov./Exp. mismatch
**V602**: TS Edit with row identifier "Legal Entity Identifier"
**V619-3**: LAR Edit with row identifier "Universal Loan Identifier"
<br>
> TS vs LAR headers + S303 Highlighting

- src/filing/institutions/InstitutionPeriodSelector.jsx
Closes #313 
Replaces `Array.from` when generating Filing Period options.
Strange that there was no error throw in IE to indicate that this unsupported method was the issue.  I see two other instances of `Array.from` in Data Publication but will open a separate ticket to address their replacement.
> [Filing] Fix Filing Period dropdown in IE

- src/filing/submission/edits/Table.jsx
Closes #317 
As part of changes to fix CSV parsing on the Platform, quotes were added around the Edit description field.
This removes them.  
Verified with the team that quotations marks are not part of the Edit description, other than those added during this parsing fix, so the global replace on that string should be safe.
> Remove Edit description quotes

- yarn.lock
Closes #319 
Re-added the dependency using `yarn add <package>@<version>`, like I was supposed to do from the beginning, and was able to complete the build.  Hopefully this eliminates the glitch for good.
> Enable yarn install to resolve @cypress/skip-test

- src/data-publication/constants/years.js
- src/data-publication/reports/SearchList.jsx
Closes #293 
- Adds 2019 to Year selection
- Adds 2019 to list of years to fetch data for
There's no indication of the year in the file name or in the content as far as I can tell.  So you can just inspect the 'Download Modified LAR' link to validate that it's pulling from the `/modified-lar/2019` bucket when `2019` is selected.
> Publish Modified LAR 2019

- src/data-publication/reports/Report.css
- src/data-publication/reports/tables/A.jsx
- src/data-publication/reports/tables/A4.jsx
- src/data-publication/reports/tables/AggregateI.jsx
- src/data-publication/reports/tables/I.jsx
Closes #345 
Besides 2017 Aggregate table i, also fixes 2018 Aggregate "Reporting Financial Institutions" and the set of A tables for 2017 for both aggregate and disclosure.
> Center narrow tables

- src/filing/App.jsx
Closes #342 
- Edit `userEnvironmentConfig.jsx` to always fetch from git hosted config
- Edit `config.json` to remove 2020-Q1 from `dev.filingPeriods`
- Navigate to 2020-Q1 filing
- Hit refresh a few a times
- Observe that the UI does not display error or hang with loading icons
> Update Redux store's filingPeriod if different from URL's

- cypress/integration/data-publication/ModifiedLAR.spec.js
Closes #344 
Test was performing an unnecessary click that changed the target year from 2017 to 2018, resulting in the expected Institution ID not being found.
> Update broken 2017 Modified LAR Cypress test

- src/filing/institutions/SubmissionHistory.jsx
Closes #362 
- Remove usage of "reversed" attribute on order list
- Add "value" attribute to line items instead
I don't have ability to test IE locally but via DOM Explorer on Citrix it looks like IE respects the "value" attribute for line items.  Looks good on Chrome, Safari locally.
> Replace ol.reversed with li.value

- src/filing/App.jsx
- src/filing/actions/fetchAllInstitutions.js
- src/filing/actions/getFilingPeriodOptions.js
- src/filing/actions/receivePeriodOptions.js
- src/filing/actions/requestPeriodOptions.js
- src/filing/institutions/InstitutionPeriodSelector.jsx
- src/filing/institutions/container.jsx
- src/filing/institutions/index.jsx
- src/filing/reducers/filingPeriodOptions.js
- src/filing/reducers/index.js
- src/homepage/index.js
Closes #354 
Changes:
- Checks for quarterly institutions for 2020+
- Filters displayed filing period options on `/institutions` page accordingly
Considerations:
- Once 2020-Q1 closes, will it be removed from the config.filingPeriods array?
- If no, then logic needs to update to use `config.filingPeriods` as source of truth
- Do we want to use the derived filing period options to determine re-routing at the `src/filing/App.jsx` level?
Testing (against Dev):
- 2020 and Q1 shown as option when QFiler associated (MEISSADIATESTBANK001)
- 2020 and Q1,Q2 shown as option when QFiler associated and config.filingQuarters has Q2 open
- 2020 not shown as option when no QFilers associated (MEISSADIATESTBANK002)
TODO:
- Cleanup `src/homepage/index.js`
- Cleanup `src/filing/App.jsx`
- More efficient …
> Filing: Only show relevant period options 

- src/data-browser/charts/MapContainer.jsx
Closes #383
Also changes the overlay line width to 1.5, which I think is much sleeker and the very heavy overlay is no longer required since the per-dataset styling was introduced
> state line overlay

- src/filing/actions/getFilingPeriodOptions.js
Closes #459 
Explicitly adds element to the Set as opposed to attempting to create the Set from the Array.
No way for me to test locally.
Filing in Dev is currently down, redirecting resources for other dev work, so can't deploy there.
Unable to test the Filing app via IE Tab (redirect from Keycloak doesn't work...).
@wpears If you can test locally against Prod, it would be appreciated.  Otherwise we can wait until Dev is free, deploy, and I can test via citrix.
> [Filing] replace "new Set(iterator)" - not supported in IE

- src/data-browser/geo/leiUtils.js
Closes #458 
If `fetchLeis` is called again before a previous fetch is finished, the old fetch(es) will automatically short-circuit.
> Bail from lei state update if leis have since been fetched

- cypress.json
- cypress/integration/data-browser/2018.spec.js
- cypress/support/helpers.js
- cypress/support/index.js
- src/data-browser/geo/ActionsWarningsErrors.jsx
- src/data-browser/geo/Geography.jsx
- src/data-browser/geo/ItemSelect.jsx
- src/data-browser/geo/LoadingButton.jsx
- src/data-browser/geo/VariableSelect.jsx
Closes #416 
- Copies over helper functions, HTML element IDs, and `data-url` tags from 2017
- Implements 2018 Data Browser tests
- Extends `defaultCommandTimout` in an attempt to address flakiness.
I'm not positive that [this change](https://github.com/cfpb/hmda-frontend/pull/486/commits/2c7cbf3681f22d49fa844641355ddb25b35cf703) actually fixes the problem, though the `Object{3}` error does seem to be resolved. 
I switched back to the old code to try to verify the fix but all tests continued to pass. 🤷
> Data Browser 2018 Cypress tests

- src/MaintenanceMessage.jsx
- src/filing/home/index.jsx
Closes #501 
Allows us to remove the announcement message if we desire
> If announcement isn't present, prevent access errors

- cypress/integration/data-browser/2017.spec.js
- cypress/integration/data-browser/Switching.spec.js
Closes #520 
Large diff due to wrapping all tests in an `if` block, changing indentation of all tests.
- Set `CYPRESS_HOST` to `dev-beta` url => Test should run and complete successfully.
- Set `CYPRESS_HOST` to `prod-default` url => Test should not run
> DB 2017 Cypress updates

- cypress/integration/data-browser/2018.spec.js
- cypress/integration/data-browser/2019.spec.js
Closes #519 
Large diff due to adding conditional block around test cases execution.
- Set `CYPRESS_HOST` to `dev-beta` url => 2018 should run, 2019 should not
- Set `CYPRESS_HOST` to `prod-default` url => Both 2018 and 2019 db tests should run
- Set `CYPRESS_HOST` to `dev-default` url => Both 2018 and 2019 db tests should run
> DB 2018 and 2019 test updates

- src/common/constants/config.json
- src/filing/institutions/container.jsx
Closes #524 
- Use the "late" filing deadlines when determining blocked actions
- Minor code cleanup
- Can use `MEISSADIATESTBANK001` in prod-default
- Update to be a quarterly filer via Help
- Update `fetchCurrentFiling.js > line 17+` 
```
// Avoid creating Filings for passed Quarters
if (isQuarterly && afterFilingPeriod(period, filingQuarters)){
console.log('No new Q filing after deadline')
return dispatch(receiveNonQFiling(institution))
}
// Test 'Create New Filing' scenario but avoid actually creating the new filing 
// to enable this LEI to be reused for these scenarios in the future.
console.log('Creating new filing')
return dispatch(receiveNonQFiling(institution))
```
- Set local keycloak and proxy to `prod-default`
- Update `filingQuartersLate` in `config.json` for `dev-default` …
> Use correct deadlines when restricting new Q-Filing creation

- src/filing/institutions/SubmissionHistory.jsx
Closes #533 
Testing against dev-default
- Use FRONTENDTESTBANK9999
- For Q2, observe the simple message shown in the screenshot above.
- For Q1, observe paginated display of history.
> [Filing] Show simple message when there is no submission history

- cypress/integration/data-publication/ModifiedLAR.spec.js
- src/data-publication/reports/Results.jsx
Closes #550 
- Enable "Include Header" for 2019
- Refactor mLAR tests to remove duplicated code.
> Reenable 2019 mlar with header

- .travis.yml
- cypress/integration/filing/Keycloak.spec.js
- src/data-browser/Select.jsx
Closes #619 
- Removes command preventing execution of full Cypress test suite
- Updates poorly written Travis config command that was causing build to fail
- Clears eslint warning about an IE workaround
> Restore running of all Cypress tests by removing .only

- cypress/wait-for-server.sh
Closes #652 
Doubling the wait time from 5 mins to 10 mins.
> Extend wait time for platform/frontend to load in CI builds

- src/common/configUtils.js
Closes #717 
Strips http:// and https:// from host name when determining environment configuration file.
> [Cypress] Pull correct env config file

- cypress/integration/data-browser/2017.spec.js
- cypress/integration/data-browser/2018.spec.js
- cypress/integration/data-browser/2019.spec.js
- cypress/support/helpers.js
Closes #732 
- More lenient checking of the HTTP status code when validating Data Browser download links.  Instead of checking exclusively for a `200`, we'll now check for any non-error code `< 400`.
- More detailed error message in the event of failure
Example of new error output.
> Reduce flakiness of Cypress link validition

- src/common/constants/dev-beta-config.json
> Open 2021 Annual and Q1 in Dev-Beta

- src/hmda-help/constants/dates.js
Closes #741 
Short term fix to enable 2021 for HMDA Help in dev-beta.
The long-term solution for HMDA Help environment configuration which will probably involve expanding the shared, GH hosted environment config files.
> Enable 2021 for HMDA Help in dev-beta

- src/homepage/index.js
Closes #735 
Adds separate 2018 FIG links for data collected with/without the 2018 HMDA rule.
> Expand 2018 FIG links

- src/data-publication/reports/Report.jsx
Closes #740 
Previously the year was hardcoded as 2018, this PR makes the value dynamic, to reflect the user's actually selections.  
- On the webpage
- In the downloaded CSV
> Dynamic year for Disclosure IRS headings

- src/documentation/FigLinks.jsx
- src/homepage/Home.css
- src/homepage/index.js
We can go ahead and merge this, then do a deployment on Friday, once the S3 update is complete.
Checks a box in #745
> Add FIG update date

- nginx/nginx.conf
Helps with Devops issue #2135
- Adds a limit of 8 simultaneous connections per IP address
- Blocks script execution in user and system folders
> Deny scripts, Limit connections

- src/common/constants/dev-beta-config.json
- src/data-browser/index.js
- src/data-browser/maps/MapContainer.jsx
The previous Redirect method can lead to a `WebGl not supported` message.  This corrects that moving the redirect outside of the affected component.
Previously:
Also fixes the order of DB years.
|Before|After|
|---|---|
|<img width="162" alt="Screen Shot 2020-12-02 at 3 10 12 PM" src="https://user-images.githubusercontent.com/2592907/100937742-b6299900-34b0-11eb-97d7-a9c955d2e681.png">|<img width="160" alt="Screen Shot 2020-12-02 at 3 10 51 PM" src="https://user-images.githubusercontent.com/2592907/100937682-98f4ca80-34b0-11eb-9ae9-5d5259a742b7.png">|
> Maps Updates

- src/tools/file-format-verification/components/FilingPeriodSelector.jsx
Closes #772 
Adds 2020 option.
> Add 2020 to FFVT

- src/hmda-help/constants/dates.js
Closes #774 
Adds 2021 for HMDA Help in all Beta environments.
> Add 2021 option to HMDA Help in Prod Beta

- src/data-browser/maps/MapsGraphs.css
- src/data-browser/maps/popupUtils.jsx
The FIPS isn't really helpful in the popup and (especially for states) could be confusing. The `per 1000 people` bit I think makes it less of a floating number with no context
> Update popup styling to be more clear

- cypress/integration/tools/CheckDigitTool.spec.js
- cypress/integration/tools/RateSpread.spec.js
- cypress/support/helpers.js
Closes #785
- Fixes pattern matching (was a string instead of regex) in `isProd` , which was causing some tests to incorrectly get skipped based on their environment.
- Updates use of Cypress.Blob API to reflect new return type for `#binaryStringToBlob`
> Cypress fixes for Rate Spread and Check Digit

- src/filing/submission/edits/Table.jsx
closes #795
- adds `V608-1` and `V608-2`  to ULI suppression list
1. Sample Test Files
[Abhinayaa.Bank_V608-2.txt](https://github.com/cfpb/hmda-frontend/files/5713617/Abhinayaa.Bank_V608-2.txt)
[Abhinayaa.Bank_V608-1-uli.48.character (1).txt](https://github.com/cfpb/hmda-frontend/files/5713615/Abhinayaa.Bank_V608-1-uli.48.character.1.txt)
-
>  Suppressing redundant ULI fields for V608-1 and V608-2

- src/tools/file-format-verification/reducers/index.js
- src/tools/lar-formatting/AppIntro.jsx
Closes #788 again.
Uses `defaultDocsPeriod` instead of `defaultPeriod` so that the original intent is met: to allow Docs/Tools to point to the upcoming Filing season separately from the Filing app options.
> Use defaultDocsPeriod instead of defaultPeriod to set period for Tools

- .gitignore
- src/filing/home/index.jsx
- src/filing/utils/keycloak.js
- src/hmda-help/index.js
- src/homepage/index.js
Closes #812 
- remove `.error()`
- remove `.success()`
> Remove deprecated Promise methods

- src/documentation/Product.jsx
- src/documentation/tools/DataBrowser.jsx
Closes #842
- Hides Documentation sections that don't have articles.
- Removes pre-release 2017 DB documentation
> 842 site updates

- src/filing/common/ErrorWarning.css
- src/filing/common/ErrorWarning.jsx
- src/filing/reducers/error.js
Close #776 
- ~Suppresses 504 errors that occur during file upload.~
- Displays status code and status text when available
> Display HTTP Status Code in Filing errors

- cypress/integration/filing/Keycloak.spec.js
- src/filing/App.jsx
Closes #901 
- Fix: Filing app was automatically redirecting to the Keycloak login page when visiting a Quarterly filing (i.e. /filing/2021-Q1/) page, preventing users from being given the option to Login or Signup. Was also breaking Keycloak specs.
- Updated Cypress specs to ensure the test user is logged out before each Keycloak test.
This is deployed to Production under v1.2.14e and the testing Pod has been updated with the latest specs, with all tests passing. 
---
Part 1 of #809   
Late addition (not in v1.2.14.e)
Redirect to latest filing period when visiting an invalid filing period i.e. /filing/3000 in [App.jsx](https://github.com/cfpb/hmda-frontend/pull/902/files#diff-0aea4518a35821b77199ef545c45a26241242ad9753c54e4f66c2293ba571955)
> [Filing] Stop auto-redirect to Keycloak login page

- cypress/integration/data-browser/2018.spec.js
- cypress/integration/data-browser/2019.spec.js
- src/common/environmentChecks.js
- src/common/useRemoteJSON.jsx
- src/tools/rate-spread/CSVUpload.jsx
- src/tools/rate-spread/Form.jsx
Closes #829
Closes #905
- [Cypress] Only run Data Browser 2018/2019 against Production
- [Rate Spread] Only use local API in CI
- [External Config] Fix bug that prevented remotely hosted config files from updating the UI.
This is currently deployed to `Dev` as `v1.2.15-pre2`, testing looks good 👍🏽
> Pre-v1.2.15 cleanup

- src/documentation/Home.jsx
Closes #914 
- Rebrands the `Other Documentation` section for the `HMDA APIs`
- Adds a short purpose description of the `HMDA APIs` section 
- Add more fine-grained links to to each API's section in the API Documentation site
> [Documentation] Expound upon HMDA API section

- src/homepage/index.js
Closes #910 
- Adds the word `Beta` in Beta environments
> [Homepage] Indicate that users are access the HMDA Beta Filing Platform

- src/data-publication/reports/DynamicDataset.jsx
Closes #916
- Removes extraneous file spec links for Panel
- Rewords and reorders file spec links for LAR files to better connect the two documents
> [DynamicDatasets] Remove Panel documentation links

- src/common/ExternalLink.jsx
- src/common/OptionCarousel.css
- src/common/OptionCarousel.jsx
- src/filing/submission/container.css
- src/filing/submission/summary/Summary.css
- src/filing/submission/summary/index.jsx
Closes #917 
- Adds some separation between Respondent Info and File Info
- Adds section descriptions
- Respondent Info description indicates that users should update/resubmit LAR to apply RI changes.
> [Filing] More Informative Filing Summary page

- src/data-browser/maps/MapsGraphs.css
- src/data-browser/maps/TextSelector.css
- src/documentation/markdown/2018/data-browser-maps-faq.md
- src/documentation/markdown/2019/data-browser-maps-faq.md
- src/documentation/markdown/2020/data-browser-maps-faq.md
Closes #993 
- Typo in Maps FAQ (secon => second)
- Fixes app crash when clearing the only selected filter
- More consistent font size and color in Maps control box
| Before | After |  
|--|--|
|<img width="415" alt="before" src="https://user-images.githubusercontent.com/2592907/120544593-d4fae080-c3aa-11eb-831c-f5d76c0bc0ed.png">|<img width="415" alt="Screen Shot 2021-06-02 at 12 36 29 PM" src="https://user-images.githubusercontent.com/2592907/120544270-746ba380-c3aa-11eb-9b69-8b0fa620a1a4.png">|
> Maps fixes

- src/documentation/Product.jsx
Closes #960 
Rate Spread documentation is not split by year, so no need to present year selection.
|Before|After|
|--|--|
|![Screen Shot 2021-06-02 at 3 06 06 PM](https://user-images.githubusercontent.com/2592907/120552993-2f993a00-c3b5-11eb-8a94-0ccd47d37cba.png)|![Screen Shot 2021-06-02 at 3 06 22 PM](https://user-images.githubusercontent.com/2592907/120552998-3162fd80-c3b5-11eb-8de2-434e5927ebde.png)|
> fix(docs): Remove year selector from Rate Spread docs

- src/common/constants/dev-config.json
- src/common/constants/prod-beta-config.json
- src/common/constants/prod-config.json
Closes #1026 
- Adds 2021-Q2 as an option in the Filing app
- Defaults the Filing app to the 2021-Q2 Filing Period
> Open 2021-Q2

- src/data-publication/ChangeLog/change-log-data.json
Closes #1021 
Adds a `Correction` to the Change Log, noting the regeneration of the Report 9 for 2019 & 2020.
> task(changelog): Agg Report 9 regeneration

- src/hmda-help/search/FilersSelectBox.jsx
Closes #1018 
The HMDA Help search box will now automatically perform an Institution search when a correctly formatted LEI is entered. This addresses a gap in the pre-populated list of Institutions.
> feat(help): autosearch for valid leis

- src/data-browser/constants/variables.js
- src/data-browser/datasets/CheckboxContainer.jsx
- src/data-browser/datasets/Geography.css
- src/data-browser/datasets/Geography.jsx
Closes #114 
Adds a button to each Filter option selector in the Data Browser to either "Select All" or 
Clear Selected".
> Data Browser - Select All button

- src/common/OptionCarousel.css
- src/common/OptionCarousel.jsx
- src/common/images/pause.svg
- src/common/images/play.svg
- src/filing/utils/date.js
- src/homepage/AnnouncementBanner.jsx
- src/homepage/index.js
Closes #869 
This PR adds a banner carousel that enables us to display multiple announcements on the HMDA homepage, in a compact space.  The carousel includes auto and manual-advance functionality, as well as the ability to pause the auto-advance. 
Additionally, we've added the ability to configure scheduled announcements.  This is designed to address the pain point of having to manually change the homepage banner to notify users about the the open/close of both Annual and Quarterly filing periods.  This will operate by displaying the following message types for the corresponding number of days:
```
const SCHEDULED_EVENT_DURATIONS = {
annualOpen: 45,    // Annual Filing period is open.
annualClose: 30,   // Annual Filing Timely deadline is passed.  Resubmissions still accepted. …
```
> Automate "Filing closed" banner

- cypress/integration/data-browser/2018.spec.js
- cypress/integration/data-browser/2019.spec.js
- src/data-browser/constants/variables.js
Closes #1047 
In the HMDA Data Browser, we previously removed the numeric Option ID from the checkbox label, but did not make the change consistent across the other page elements that display the label. This PR corrects that inconsistency in both the UI and the Cypress tests.
|before|after|
|--|--|
|<img width="473" alt="Screen Shot 2021-07-26 at 2 40 43 PM" src="https://user-images.githubusercontent.com/2592907/127056514-24b4df17-32a2-4691-8e92-58aa9b3d04ce.png">|<img width="474" alt="Screen Shot 2021-07-26 at 2 41 00 PM" src="https://user-images.githubusercontent.com/2592907/127056533-0e25d4b3-a7e1-4e66-98fb-71a907ce7bb4.png">|
> fix(databrowser): Remove option ID from all displayed instances

- src/documentation/markdown/2017/panel-data-fields.md
- src/documentation/markdown/2018/panel-data-fields.md
- src/documentation/markdown/2019/panel-data-fields.md
- src/documentation/markdown/2020/panel-data-fields.md
- src/documentation/markdown/2021/panel-data-fields.md
Closes #1062 
- Fixes an unescaped underscore, which was causing an anchor tag to be mis-rendered
- Removes a hyphen in an anchor label, which was causing an additional paragraph tag to be rendered, resulting in the anchor being incorrectly placed on a new line.
|before|after|
|--|--|
|<img width="949" alt="Screen Shot 2021-08-10 at 5 32 01 PM" src="https://user-images.githubusercontent.com/2592907/128948951-ad1d4681-0f22-476d-a5c9-b3a307a619a2.png">|<img width="942" alt="Screen Shot 2021-08-10 at 5 34 38 PM" src="https://user-images.githubusercontent.com/2592907/128948957-d0f422de-3c76-43f7-a3cd-d8d0c5089a8a.png">|
> fix: Documentation formatting

- src/app.css
- src/common/Alert.css
- src/filing/common/Header.jsx
- src/filing/institutions/HeaderOpen.jsx
- src/filing/institutions/ViewButton.jsx
- src/filing/modals/Modal.css
- src/filing/modals/confirmationModal/RefileText.css
- src/filing/modals/confirmationModal/RefileText.jsx
- src/filing/modals/confirmationModal/container.jsx
- src/filing/modals/confirmationModal/index.jsx
- src/filing/submission/ReadyToSign.jsx
- src/filing/submission/signature/index.jsx
Closes #1055 
- Site Header: Indicate 'Beta Platform' vs 'Filing Platform'
- Banner: Add link to Beta platform in the Production filing banner
- Upload: Provide additional details of the ramifications when uploading a file which will replace a previous submission. Include institution name and the filing period for the current submission. 
- Signing: Simplify the language around the signing of a submission 
|prod|beta|
|--|--|
|<img width="382" alt="Screen Shot 2021-08-10 at 4 14 17 PM" src="https://user-images.githubusercontent.com/2592907/128942068-4e72e197-56fd-4005-baf7-a912f38b5717.png">|<img width="376" alt="Screen Shot 2021-08-10 at 4 14 43 PM" src="https://user-images.githubusercontent.com/2592907/128942084-b3c5091a-3fda-4d77-8afd-1da688b47b34.png">|
|prod|beta|
|--|--|
| <img …
> feat: Additional visual cues for Production environment

- src/common/OptionCarousel.css
- src/homepage/AnnouncementBanner.jsx
Closes #1074 
- Allows multiple announcements to be configured via external configuration files (i.e. prod-config.json, dev-config.json)
- Extends the number of days for which we show "X filing period is open" to 60 days
- CSS adjustment to allow announcement banner text to be user-selectable.
Note: This PR is a precursor to publishing the extended downtime announcement banner. 
Example of single announcement config:
```
"announcement":  {
"message": "On June 17, 2021, the Disclosure Reports, MSA/MD Aggregate Reports, Snapshot National Loan-Level dataset, and Dynamic National Loan-Level dataset for 2020 were released. These files are accessible from the ",
"type": "info",
"heading": "Data Publication Release",
"link": {
"url": "https://ffiec.cfpb.gov/data-publication/",
"text": "HMDA Data …
```
> Enable multiple configured homepage announcements

- src/common/constants/dev-config.json
- src/common/constants/prod-beta-config.json
- src/common/constants/prod-config.json
Closes #1076 
<strike>Note: Dependent on the deployment of changes in #1074</strike> (Complete ✅ )
Adds banners announcing the extended downtime to both the HMDA homepage and the Filing app, for Prod and Beta environments.
> Announce Extended Downtime

- src/data-publication/ChangeLog/change-log-data.json
- src/homepage/index.js
Closes #1109 
Adds homepage links for 2022 FIG and Supplemental Quarterly
Update Change Log with release announcement
> feat(fig): add homepage links for FIG and Supplemental 2022

- .gitignore
- README.md
- package.json
- src/data-publication/reports/snapshot/index.jsx
- src/documentation/markdown/2017/arid2017-to-lei-schema.md
- src/documentation/markdown/2017/identifiers-faq.md
- src/documentation/markdown/2017/panel-data-fields.md
- src/documentation/markdown/2018/arid2017-to-lei-schema.md
- src/documentation/markdown/2018/identifiers-faq.md
- src/documentation/markdown/2018/panel-data-fields.md
- src/documentation/markdown/2019/arid2017-to-lei-schema.md
- src/documentation/markdown/2019/identifiers-faq.md
- src/documentation/markdown/2019/panel-data-fields.md
- src/documentation/markdown/2020/arid2017-to-lei-schema.md
- src/documentation/markdown/2020/identifiers-faq.md
- src/documentation/markdown/2020/panel-data-fields.md
- src/documentation/markdown/2020/public-panel-schema.md
- src/documentation/markdown/2021/arid2017-to-lei-schema.md
- src/documentation/markdown/2021/identifiers-faq.md
- src/documentation/markdown/2021/panel-data-fields.md
- src/documentation/markdown/2021/public-panel-schema.md
- src/documentation/markdownUtils.js
- src/documentation/publications/SnapshotDynamic.jsx
Closes #1067 
Replaces the methodology for matching ARID2017 to LEI with links to the new reference table. Fixes formatting.
|Before|After|
|--|--|
|<img width="951" alt="Identifier-before" src="https://user-images.githubusercontent.com/2592907/134245712-d479725d-7d2b-4a61-8597-7e231e51c7df.png">|<img width="919" alt="Identifier-after" src="https://user-images.githubusercontent.com/2592907/134245802-6dcd7d49-feec-4fcb-b120-a471c047c422.png">|
Replaces the methodology with a link to `Snapshot Dataset` page so users can access the reference table.
Deletes this entry for 2020 and 2021.
|Before|After|
|--|--|
|<img width="957" alt="Panel-before" src="https://user-images.githubusercontent.com/2592907/134245647-d0001a5b-2f55-4048-9141-4c75c5d0e55c.png">|<img width="962" alt="Panel-after" …
> ARID2017 Documentation Integration

- src/common/constants/dev-beta-config.json
- src/common/constants/dev-config.json
- src/common/constants/prod-beta-config.json
- src/common/constants/prod-config.json
Closes #1130 
- Removes the post-migration all-clear message
- Updates the `dev-beta-config` to use an array of announcement messages
> Remove the all-clear announcement

- cypress/Dockerfile
- package.json
Closes #1135 
- Expand definition of compatible Node engines
- Update Cypress installation method in the testing pod
> Update Cypress testing pod build process

- src/documentation/markdown/2018/data-browser-faq.md
- src/documentation/markdown/2019/data-browser-faq.md
- src/documentation/markdown/2020/data-browser-faq.md
- src/documentation/markdown/2021/data-browser-faq.md
Closes #414 
- Adds the freeze date for the 2020 dataset.
- Lists freeze dates in a table for improved readability and expansion
- Changes `static dataset` to `Snapshot dataset` for clarity and consistency
|Before|After|
|---|---|
|<img width="954" alt="Screen Shot 2021-10-19 at 4 42 29 PM" src="https://user-images.githubusercontent.com/2592907/138000675-c86570e4-525e-48d3-84c4-0fa062c8624c.png">|<img width="419" alt="Screen Shot 2021-10-19 at 4 39 15 PM" src="https://user-images.githubusercontent.com/2592907/138000522-9734f453-608e-41f8-ab7e-a15fa9b8f446.png">|
- run `yarn dev-docs`
- run `yarn ci`
- Visit http://localhost:3000/documentation/2021/data-browser-faq/
> Data Browser FAQ - Update dataset freeze dates

- src/common/mailingListServices.jsx
Closes #1202
I believe that because of the way our Alert component clones its children, we must wrap this `message` string in a Fragment.  Otherwise the Frontend crashes.
> Wrap Alert child string in a Fragment

- src/common/constants/dev-config.json
- src/common/constants/prod-beta-config.json
- src/common/constants/prod-config.json
Closes #1181 
[Part 1](https://github.com/cfpb/hmda-frontend/pull/1219) has been **deployed**. This PR can be merged to display the requisite Filing banner.
> Filing Banner - 2018 collection will end

- src/tools/file-format-verification/actions/index.js
- src/tools/file-format-verification/containers/UploadForm.jsx
Closes #1270 
We've established that there is only one FFVT parser for all years, and we no longer accept user-input on which year the submitted file is for, so we no longer need to check for valid years in the FFVT parsing logic.
> FFVT - Remove year checks

- src/homepage/AnnouncementBanner.jsx
Closes #1287
- When we are in a Quarterly period, the previous calendar year is the latest open annual filing period; Else our default period is already the latest annual filing period, so we use it
- End of annual collection happens in data year + 4 (ex. 2018 collection ends in 2018+4 = 2022), so we should be checking for closure events accordingly (current year - 4 = 2022 - 4 = 2018).
> Announcement Banner - Use the correct annual filing year when checking for events

- src/common/MailingListSignup.jsx
- src/common/MailingListSignupForm.css
Closes #1297 
- Extracts PRA link into reusable component
- Adds link to MailingList.large
Link is responsively aligned with the form's submit button:
small screen | larger screen
---|---
> Consistent PRA Link on mailing list form

- babel.config.js
- src/common/constants/configHelpers.js
- src/common/constants/configHelpers.spec.js
Closes #1294
- More nuanced derivation of Admin-selectable years to automatically provide access 
- Adds unit tests for `getFilingYears`
This fix will resolve the current Cypress error on prod-beta in the Institutions test suite where we attempt to create an Institution for a year too far in the future.
> HMDA Help - Admin-selectable years

- src/filing/actions/receiveFiling.js
- src/filing/actions/receiveLatestSubmission.js
- src/filing/actions/receiveSubmission.js
- src/filing/institutions/Institution.jsx
- src/filing/institutions/Progress.jsx
- src/filing/institutions/Status.jsx
- src/filing/institutions/ViewButton.jsx
- src/filing/institutions/helpers.js
- src/filing/reducers/latestSubmissions.js
- src/filing/reducers/submission.js
- src/filing/utils/date.js
Closes #1115 
- Display the `stalled upload` status if an Upload is not processed after 5hrs.
- Improve accuracy of `SubmissionNav` upload status indicator.
- Display `Refile` button, prompting user to re-upload, when `stalled`.
1. Paste the following snippet in `src/filing/institutions/Institution.jsx` at line 20
```
submission = {
id: {
lei: 'FRONTENDTESTBANK9999',
period: { year: 2019, quarter: null },
sequenceNumber: 1005,
},
status: {
code: 3,
message: 'Your file has been uploaded.',
description: 'Your data is ready to be analyzed.',
},
start: 1640650476515,
end: 0,
fileName: '2019-FRONTENDTESTBANK9999.txt',
receipt: '',
signerUsername: null,
qualityVerified: false,
macroVerified: false,
qualityExists: false,
macroExists: false,
isStalled: true,
}
```
2. Visit …
> [Filing] Stalled uploads

- src/filing/actions/receiveFiling.js
- src/filing/actions/receiveLatestSubmission.js
- src/filing/institutions/Institution.jsx
Closes #1326 
- Stalled Upload check - guard destructuring to avoid error
- Institutions: Add Filing Period and fallback where appropriate
- Start HMDA Platform / Institutions API locally
- Frontend on `master`: `yarn ci-data && yarn ci`
- Visit http://localhost:3000/filing and observe that institutions are stuck in loading status for all periods
- Frontend: `git checkout 1326-bad-destructure`
- Visit http://localhost:3000/filing and observe that institutions are loading for all periods
> Guard destructuring

- src/common/configUtils.js
Closes #1328 
- Set the Beta config's `defaultPeriod` to match Production's `defaultPeriod`
https://user-images.githubusercontent.com/2592907/151609339-60c1fb35-c765-42bf-8b99-b2b301edf1e4.mov
1. Change [App](https://github.com/cfpb/hmda-frontend/blob/master/src/App.jsx#L30) to use Beta config:
```
const config = useEnvironmentConfig('beta')
```
2. Visit http://localhost:3000/filing
3. Observe that you are redirected to `2021` like in Prod vs `2022` like in Beta
- This redirection happens based on the in-build configurations, before the fetched config can have any effect. Once I realized that, I was able to figured out the right place to make the adjustment.
> [Beta][Filing] Match the defaultPeriod to Production

- src/filing/institutions/Progress.jsx
- src/filing/submission/Nav.jsx
- src/filing/submission/router.jsx
- src/filing/submission/upload/DropzoneContent.jsx
Closes #1320
- Updates the UI indicator for `Syntactical & Validity` edits once the Submission's status has reached `8 - No Syntactical or Validity edits`
- Submission Nav
- Progress Nav
- More accurate language in the Upload dropzone to indicate when the file is being `Analyzed` instead of `Uploaded`.
The file is still being analyzed, but we know that it does not have SV edits, so we mark that step as done.
before|after
---|---
We also indicate `Analysis` in the dropzone text since the file is uploaded but still being checked for Edits.
before|after
---|---
> Update Submission Nav

- src/filing/utils/checkFileErrors.js
Closes #1311
- Checks file encoding of uploads `if (fileInfo.encoding !== 'UTF-8')`
- Moves other checks inside of `detectFileEncoding` promise for consistency. 
1. I've run 5 1M row submissions through this check and have not found any memory spikes
> [Filing] Block non-UTF8 encoded file uploads with message

- src/common/constants/dev-config.json
Part of #1377 
Adds 2021 as an option on the Modified LAR page in the `DEV` environment.
> [ModifiedLAR][Config] Add 2021 option to MLAR page

- src/common/constants/dev-config.json
- src/common/constants/prod-beta-config.json
- src/common/constants/prod-config.json
Closes #1381 
Adds a banner, guiding users to the Census product release schedule.
> [Announcement] 2022 FFIC Census Product schedule

- src/common/constants/dev-config.json
- src/common/constants/prod-beta-config.json
- src/common/constants/prod-config.json
Adds a missing space between the main message and the link to the product schedule
> [Announcement] 2022 FFIC Census Products schedule - fix spacing

- src/common/constants/dev-config.json
- src/common/constants/prod-beta-config.json
- src/common/constants/prod-config.json
- src/data-publication/ChangeLog/change-log-data.json
Closes #1377 
- Adds banner announcing release
- Add Updates/Notes entry for release
- Adds `2021` option to the UI via `prod-config.json`
- Homepage banner
- Release notes
> Modified LAR 2021 - Part 2 (Release)

- cypress/Dockerfile
- cypress/docker-runner.sh
Closes #1395 
- Removes load test file from `Dockerfile` build
- `curl`s  compressed Submission file for load testing from S3 and unzips
Changes in this PR are successfully running in our current Cypress test image for Production.
> [Cypress] Pull load file from S3 into running pod

- src/filing/home/container.jsx
- src/filing/home/index.jsx
Closes #1376 
The original goal was to add display of Maintenance announcements on the Filing page.  I found that this functionality was already in place but had some bugs.  This PR, in conjunction with a DevOps PR to fix the Maintenance PR generation script, will enable the desired message display. 
We had multiple areas where we would display the `config.filingAnnouncement` message, but there was an error in the way this configuration was being passed down to the target component, so one of those areas would never actually display the message.  When I fixed the error with prop-passing I found that a `Maintenance` message could wind up being shown multiple times on the Filing homepage.  So this PR eliminates that duplication. 
Observing this duplication led me to investigate the …
> [Filing] Fix display of Maintenance messaging on the Filing app

- src/common/constants/platform-messages.js
- src/filing/actions/fetchNewFiling.js
Closes #1344 
If the Frontend attempts to create a new Filing for a period that is closed (i.e. When a filer has no Filing nor any submissions), and receives a status message that starts with `The provided year or quarter is no longer available`, we appropriately display that those institutions have no filings. 
This scenario should not occur as we already have Timed Guard based checks to avoid attempting to create Filings for closed periods, but this is a fail-safe for the case where the Frontend and Backend are out of sync.
Local Frontend pointed at Production
> Open Frontend but closed Backend

- src/deriveConfig.js
- src/deriveConfig.test.js
- src/filing/utils/date.js
- src/filing/utils/date.test.js
Closes #1408 
- Adjusts Timed Guard calculations to account for DST
- Adds `jest` tests for modified functions
- Cleans up some outdated `jests` tests
- `yarn run jest src/deriveConfig.test.js`
- `yarn run jest src/filing/utils/date.test.js`
> [Filing] Account for Daylight Savings Time

- cypress/docker-runner.sh
Closes #1410 
Testing - Cypress pod successfully completed Integration and Load testing last night.
> [Cypress] Use `unzip` instead of `tar`

- cypress/integration/tools/RateSpread.spec.js
Closes #1429 
This API does not run in our Beta environment, hence we're updating the conditional logic to correctly skip this test.
> [Cypress] Skip Rate Spread API test in Beta

- cypress/Dockerfile
- cypress/integration/tools/RateSpread.spec.js
- src/deriveConfig.js
- src/deriveConfig.test.js
Closes #1430 
Our test pods run in UTC, which means the current method of calculating the adjustment to Eastern Time may incorrectly result in the DateTime moving forward (subtracting a negative `offset`) instead of backwards (subtracting a positive `offset`).
> [Cypress] Avoid negative timezone offsets

- src/data-publication/reports/snapshot/index.jsx
Closes #1443 
Currently, links for pipe-delimited files incorrectly point to the CSV version.  This PR directs those links to the .txt (PSV) files.
> [Data Pub] Point pipe-delimited links to PSV files

- src/common/constants/prod-beta-config.json
Closes #1452 
Changes were made as part of 2021 Data Publication release testing but should not have been merged to the main branch. As a result, Cypress testing against the Beta environment are failing.
> [Beta] Revert config changes

- cypress/integration/common-features/redirection.spec.js
- src/common/withYearValidation.js
- src/data-publication/index.js
- src/data-publication/reports/DynamicDataset.jsx
Closes #1478 
- Avoids auto-redirect from base URL in Disclosure/Aggregate Reports, which prevents users from being able to switch the selected reporting year
- Updates Cypress tests
> Fix Disclosure/Aggregate Report year switching

- src/documentation/markdown/2017/panel-data-fields.md
- src/documentation/markdown/2018/panel-data-fields.md
- src/documentation/markdown/2019/panel-data-fields.md
- src/documentation/markdown/2020/panel-data-fields.md
- src/documentation/markdown/2021/panel-data-fields.md
- src/documentation/markdown/2022/panel-data-fields.md
Closes #1482 
Add the missing -1 enumeration for `other_lender_code` in the `Public Panel - Data Fields with Values and Definitions` documentation.
> [Docs] Panel - Add enumeration -1

- cypress/integration/data-publication/ChangeLog.spec.js
Closes #1492
- Updates the `Adds filters to URL` test to check for a minimum account, as opposed to a specific count
- Deployed to Monitoring pod on 7/28
> [Cypress] Update Change Log tests

- src/documentation/publications/ModifiedLar.jsx
Closes #1504 
- Updates URLs of documentation hosted in the HMDA Platform repo
> [Docs] Fix broken links to Platform hosted documentation

- src/data-publication/reports/SupportingDocs.jsx
Closes #1541 
The Platform docs were moved a level higher, eliminating the `/v2/` folder. 
Modified LAR schema is missing on the Platform docs, so pointing that link to the Frontend documentation page.
> [ModifiedLAR] Correct links to Platform docs

- src/documentation/tools/DataBrowser.jsx
- src/documentation/tools/FFVT.jsx
- src/documentation/tools/LARFT.jsx
- src/documentation/tools/RateSpread.jsx
Part 2 of #1517 
Adds the entries needed to display the Tools docs in https://ffiec.cfpb.gov/documentation/
> [Docs] Add 2023 tools docs

- src/common/constants/dev-config.json
- src/common/constants/prod-beta-config.json
- src/common/constants/prod-config.json
Closes #1545 
Displays banner in Prod and ProdBeta announcing FIG / Supplemental Quarterly Filers Guide for 2023.
`here` links to https://ffiec.cfpb.gov/documentation/2023/fig
> [Homepage] Banner for 2023 FIG release

- src/documentation/FigLinks.jsx
PR fixes links that point to wrong supplement guide documents.
2021 and 2022 supplemental guide links now link to the correct documents.
> [Links] Fixed supplemental guide links for 2021 and 2022.

- src/documentation/markdown/2018/panel-data-fields.md
- src/documentation/markdown/2019/panel-data-fields.md
- src/documentation/markdown/2020/panel-data-fields.md
- src/documentation/markdown/2021/panel-data-fields.md
- src/documentation/markdown/2022/panel-data-fields.md
- src/documentation/markdown/2023/panel-data-fields.md
Closes #1554 
- Extends `Assets` definition per #1554
- Removes incorrect inclusion of `arid_2017` in some years, as verified against the [Panel - Schema](https://ffiec.cfpb.gov/documentation/2022/public-panel-schema/)
> [Docs] Update and correct Panel Data Fields - values/definitions

- src/data-browser/graphs/Graph.jsx
- src/data-browser/graphs/highchartsConfig.js
- src/data-browser/graphs/quarterly/SectionGraphs.jsx
- src/data-browser/graphs/quarterly/useManageGraphSelection.jsx
Closes #1530 
- Display data table values with API configured precision
- Switch thousands separator from `space` to `comma`
> [Graphs] Numeric formatting

- src/common/s3/fileProxy.js
- src/data-publication/reports/Results.jsx
- src/filing/api/fetch.js
- src/filing/submission/irs/DownloadIRS.jsx
- src/filing/submission/irs/DownloadStatus.jsx
- src/filing/submission/irs/IRSReport.css
- src/filing/submission/irs/index.jsx
Closes #1547
- Updates `fetchData` to accept a specific URL
- Fetches IRS reports via HMDA File Proxy instead of from S3
- Displays a success/not-found message for each download attempt.
- Fetches MLAR reports via HMDA File Proxy instead of from S3 
|Status|Visual|
|---|---|
|null => No click yet|<img width="560" alt="null" src="https://user-images.githubusercontent.com/2592907/193162180-916a123e-fb01-48c8-8a98-cf177b3497d1.png">|
|false => No IRS found | <img width="558" alt="false" src="https://user-images.githubusercontent.com/2592907/193162228-61960eb5-ddb4-4a98-a0c5-a4e2d66f51f2.png"> |
|true => IRS found | <img width="595" alt="true" src="https://user-images.githubusercontent.com/2592907/193162274-b7989153-283c-46ab-81dc-fde32bc49b98.png">|
- Visit …
> Use HMDA file proxy for MLAR and IRS download

- src/common/constants/dev-config.json
- src/common/constants/prod-beta-config.json
- src/common/constants/prod-config.json
Closes #1582 
Prod: Keeps only the Quarterly Graphs Update, Q3 Open, Census Schedule banners.
Beta: Also keeps the OLARFT banner.
NOTE The Q3 open banner is programmatically added so does not show up in the Configuration files.
> [Homepage] Banner cleanup

- src/common/SimpleSortTable.jsx
- src/data-browser/graphs/quarterly/QuarterlyFilersTable.jsx
- src/data-publication/reports/tables/AggregateUtils.js
Closes #1579
New button has been added to `/filers`. This allows users to be able to download filer loan and application counts table as a CSV file. Any filtering/sorting on the table will be reflected in the CSV file.
> [Graphs] Users can download filer loan info from filer tab in Graphs

- src/data-browser/graphs/graphs.css
- src/data-browser/graphs/highchartsConfig.js
Closes #1614
- Adds responsive rules to display chart at a height of 600px on mobile/tablet devices
- Adds scrolling to chart data tables
http://localhost:3000/data-browser/graphs/quarterly/ltv-fha-re?periodLow=2019-Q1&periodHigh=2022-Q2&visibleSeries=Asian,Black,Hispanic,White
1. Proxy to Dev
1. View chart on mobile device
2. (OR) Use browser responsive tools to view chart at smaller device widths
3. Verify that the chart content is visible
4. Verify that you can interact with the chart
5. Verify that you can view all table content without it affecting the overall width of the page
|before|after|
|---|---|
|<img width="972" alt="Screen Shot 2022-10-15 at 12 45 53 AM" src="https://user-images.githubusercontent.com/2592907/195975808-3aa56ef4-59aa-4c9b-a1c4-161b4cae53dc.png">|<img …
> [Charts] Usable on mobile

- cypress/integration/filing/Filing.spec.js
- cypress/integration/hmda-help/institution.spec.js
- cypress/integration/hmda-help/publication.spec.js
- cypress/integration/load/LargeFiler.spec.js
- cypress/support/index.js
- src/filing/App.jsx
- src/hmda-help/index.js
Closes #1621 
This is tested in DEV and looks good.  I don't want it merged yet, in case we need to do any deployments to other environments where PKCE is not yet enabled.  Hence leaving in as `Draft` for now.  
- Incorporates and expands upon PKCE inclusion from https://github.com/cfpb/hmda-frontend/pull/1612
- Update Cypress login flow to use UI instead API due to failures after PKCE implementation
> [Keycloak] Use Proof Key for Code Exchange (PKCE)

- cypress/README.md
- cypress/docker-runner.sh
- cypress/support/shell-helpers.sh
- cypress/update-s3-files.sh
- package.json
Closes #1628 
Closes #1627 
Changes to support new process of hosting specs/fixtures on S3 and pulling those files into the Cypress test pod at runtime in order to enable dynamic updates to test data without image rebuild.
Also adds new ENV variables to control which tests are run. 
New process:
1) Run cypress/update-s3-files.sh to upload test data and specs from the current local branch to S3.
2) Define ENV vars as outlined in cypress/README.md to configure which tests will run
3) Build and push Cypress test image (only needed for Cypress version updates or security fixes)
> 1628 refactor cypress image

- src/common/TableOfContents.jsx
- src/data-browser/graphs/graphs.css
- src/data-browser/graphs/quarterly/index.jsx
- src/documentation/DynamicRenderer.jsx
- src/documentation/index.css
- src/documentation/index.js
Closes #1620
Graphs FAQ page now displays table of contents side bar.
> [Graphs] Adds table of contents sidebar to the 'faq' page

- src/common/useAutoAdvance.jsx
Closes #1705
Updated useAutoAdvance.jsx to clearTimeout if only one Announcement is available.
> Updated autoAdvance for Single Announcement

- src/data-browser/graphs/quarterly/QuarterlyFilersTable.jsx
- src/data-browser/graphs/quarterly/useLatestAvailableYear.jsx
Closes #1711 
Derive year for Filers from graph data.
If the Graphs API says 2023-Q1 data is the latest available, then filer info for 2023 should also be ready. 
When latest is 2022-Q3 or 2022 annual, we use 2022.
> Graphs: Derive year for Filers from graph data

- src/data-browser/graphs/quarterly/SectionGraphs.jsx
- src/data-browser/graphs/utils/menuHelpers.js
Closes #1723 
- Allows users to quickly continue exploring the list of available graphs without having to manually scroll
> [Graphs] Focus Graph selection menu on current selection

- cypress/e2e/tools/RateSpread.spec.js
Closes #1746 
**Note: Test only runs when testing against Prod default (ffiec.cfpb.gov)**
Adds a Cypress test that will
- search Google for "hmda rate spread"
- Click on the HMDA link 
- Verify ability to access page from an external referrer by generating a rate spread
- `yarn cypress open --env HOST="https://ffiec.cfpb.gov"`
- Run `RateSpread.spec.js`
> [Cypress] Test access to Rate Spread from an external referrer

- cypress/e2e/filing/Filing.spec.js
- cypress/e2e/filing/Keycloak.spec.js
- cypress/e2e/hmda-help/institution.spec.js
- cypress/e2e/hmda-help/publication.spec.js
- cypress/e2e/load/LargeFiler.spec.js
- cypress/support/e2e.js
Closes #1693 
Logout calls are not interfering with testing via our nightly cronjob but are a blocker when running from localhost.  Cypress has implemented `test isolation` which makes these logout calls redundant.  
- Remove calls to cy.logout
- Remove unused param in cy.hmdaLogin
- Remove unused environment variable
> [Cypress] Remove logout calls

- src/documentation/index.js
Fixes a redirect issue where `/documentation` route wasn't being handled. PR will now properly redirect the user to Docusaurus when they enter `/documentation`.
> [Redirect] /documentation is properly handled and points to Docusaurus

- src/common/constants/links.js
Fixes #1808
Updated Menu name to 'Aggregate Reports'
> Correct name of aggregate reports in the navbar dropdown

- src/data-browser/graphs/quarterly/QuarterlyFilersTable.jsx
Removes the yearly specific year from the header on the [filer info tab](https://ffiec.cfpb.gov/data-browser/graphs/quarterly/info/filers) on graphs.
> [Filer Info] Heading content change

- src/common/constants/dev-config.json
- src/common/constants/prod-beta-config.json
- src/common/constants/prod-config.json
> [Banners] Update announcement banners on production

- cypress/e2e/common-features/redirection.spec.js
- cypress/e2e/data-browser/graphs.spec.js
- cypress/e2e/data-browser/maps.spec.js
- cypress/e2e/data-publication/AggregateReports.spec.js
- cypress/e2e/data-publication/CombinedMLAR.spec.js
- cypress/e2e/data-publication/DisclosureReports.spec.js
- cypress/e2e/data-publication/DynamicDatasets.spec.js
- cypress/e2e/data-publication/ModifiedLAR.spec.js
- cypress/e2e/data-publication/NationalAggregateReports.spec.js
- cypress/e2e/data-publication/SnapshotDatasets.spec.js
- cypress/e2e/hmda-help/institution.spec.js
- cypress/e2e/hmda-help/publication.spec.js
- cypress/e2e/tools/CheckDigitTool.spec.js
- cypress/e2e/tools/FFVT.spec.js
- cypress/e2e/tools/RateSpread.spec.js
- cypress/e2e/tools/olarft.spec.js
- cypress/e2e/updates-notes/ChangeLog.spec.js
- cypress/support/e2e.js
Closes #1975
Recommend opening Cypress for Dev, Prod Beta and Prod and run Cypress against all environments. 
**Filing** and **Keycloak** test files are the only tests that should run in `Prod Beta`.
Production should have all test files running except for two files:
- https://github.com/cfpb/hmda-frontend/blob/master/cypress/e2e/data-browser/dataset-filtering-2017.spec.js
- https://github.com/cfpb/hmda-frontend/blob/master/cypress/e2e/data-browser/Switching.spec.js
Dev should have all tests files running except for three files:
- https://github.com/cfpb/hmda-frontend/blob/master/cypress/e2e/data-browser/dataset-filtering-2017.spec.js
- https://github.com/cfpb/hmda-frontend/blob/master/cypress/e2e/data-browser/Switching.spec.js
- …
> [Cypress] Update test files for Beta

- cypress/support/e2e.js
- cypress/support/shell-helpers.sh
Closes #2044
PR to remove `rm: cannot remove 'output_integration.txt': No such file or directory` warning from our logs.
> [Cypress] Updates Shell Helper Script

- src/updates-notes/change-log-data.json
> Updated change log for V695 correction

- src/tools/lar-formatting/AppIntro.jsx
Updated ```<Link> ``` to ```<a>``` for the link to /documenation. Closes ticket Fix Excel LARFT Docs Link #2099. Working in dev.
> Fixed doc link. 

- src/data-browser/graphs/PeriodSelectors.jsx
Updated dateRange logic to limit periodLow options to less than periodHigh selection. Closes 2153.
> Bug fix for Graphs dateRange selector

- cypress/e2e/data-publication/DisclosureReports.spec.js
- cypress/e2e/filing/Keycloak.spec.js
- package.json
- yarn.lock
Closes #2151 
- Removed the `.only` check on one of the tests in the `Keycloak` test file.
- Updated `DisclosureReport` test file by adding `force: true` to the click events to ensure the click event fires. Sometimes the click event would not go off through the Cypress test runner UI resulting in false failures of the test.
Tests passed on DEV ✅
> [Vite] Upgrade from 5.1.1 to the latest version 5.2.8

- src/filing/submission/Nav.jsx
- src/filing/submission/container.jsx
- src/filing/submission/router.jsx
- src/filing/submission/signature/Signature.jsx
- src/filing/submission/summary/Summary.jsx
Closes #2169 
PR includes the following changes:
- Address the bug where navigating to the `/submission` route would redirect users to `/upload`
- Deleted a bit of code related to scroll calculations for having the Progress navigation to be fixed
- This fixed a visual bug that caused the elements below the Navigation to be hidden until the user scrolled on the page
- Fixed some `propType` warnings from the browser console
> [Filing] Fix submission route navigation

- nginx/nginx.conf
Closes #4318 in hmda-devops and #2192 in hmda-frontend
> Removed unsafe-inline from CSP. Whitelisted dap Analytics.

- cypress/e2e/filing/Filing.spec.js
- src/filing/profile/CompleteProfile.jsx
- src/filing/profile/Profile.css
Closes #2121 
Adds the ability for any vendor to get their auth token.
> [Profile Page] Auth Token

- src/data-publication/reports/snapshot/SnapshotDataset.jsx
- src/data-publication/reports/snapshot/snapshotHelpers.jsx
Closes #2254
Removes note about files not being available from the UI for 2022 One Year and 2020 Three Year `panel` files.
> [Panel] Removes note from UI

- cypress/e2e/data-browser/maps.spec.js
Closes #2253 
Further adds test coverage for Maps at the state and county level.
State level coverage for the following years: 2018, 2020, and 2022
County level coverage for the following years: 2019, 2021, 2022 and 2023
Tests are passing against production ✅
> [Cypress + Maps] Add additional test coverage for State and County

- src/common/ExpandableSection.css
- src/data-browser/graphs/Graph.jsx
- src/data-browser/graphs/highchartsConfig.js
- src/data-browser/graphs/quarterly/DataTable.jsx
- src/data-browser/graphs/quarterly/SectionGraphs.jsx
- src/data-browser/graphs/quarterly/useTableData.jsx
Closes #2252 
The automatic `HighCharts` data table is now being handled manually. The reason for this is to allow the data table styling to be better controlled. 
The data table under the graph is now expandable (closed by default).
Additionally a note about the gaps in the graph and table now appears in the UI under the custom data table.
Tests are passing against DEV ✅
> [Graphs] Data Table Expandable & Data Issue Note

- public/sitemap.xml
- src/common/constants/links.js
- src/homepage/ForFilers/FilingGuides.jsx
- src/homepage/QuickLinks.jsx
> [Homepage] 2025 FIG Release

- src/common/Header.jsx
Updated `<Header />` component logic to use the `isBeta` flag to use an `a` tag HTML element or `Link` from `react-router-dom` to resolve an issue where navigating from the homepage on BETA to `/filing` was causing it to crash.
> [BETA] Temporary Fix for `/filing` navigation

- src/updates-notes/change-log-data.json
Closes #2305
Adds 2024-Q2 graphs release entry to the change-log.
> [Change Log] Adds 2024-Q2 Graph Release

- cypress/e2e/data-browser/graphs.spec.js
Closes #2308 
Improve test coverage for the `Filer Info` tab found in the [Graphs UI](https://ffiec.cfpb.gov/data-browser/graphs/quarterly/info/filers).
> [Cypress/Graphs] Improves Test Coverage for Filer Info Tab

- src/common/constants/prod-beta-config.json
Resolves the banner maintenance confusion on production beta site. Update the prod beta banner to say the service is unavailable.
> Resolves Prod Beta Banner due to Maintenance Script

- cypress/e2e/filing/Keycloak.spec.js
- src/filing/common/LoginHeader.css
- src/filing/common/LoginHeader.jsx
Closes #2353 & Closes #2354
The Login button now says `Sign in with {LoginGov Logo}` and the `Create an Account` button was removed.
> Filing Landing Page Login/Create an Account button Update & Cypress Keycloak Test Skip

- src/common/constants/dev-config.json
🚀 It's currently up on dev: `3.2.2f` 🚀
- Adds `2024` to `mlarReleaseYear` and `dataPublicationYears.mlar` to `dev-config.json`
1. `dataPublicationYears.mlar`- Does [this page](https://ffiec.cfpb.gov/data-publication/modified-lar/2023) display `2024` mLAR data by institution? (with full data and combined mLAR data coming once the backend completes running the data pipeline for it)
2. `mlarReleaseYear` - Does the link on the home page direct to `2024` mLAR data?
Related to: #2415 
Closes: #2416
> [MLAR] Add 2024 MLAR to dev env config

- package.json
- yarn.lock
Let's fix up the remaining high and moderate severity vulnerabilities. This goes through and cherry-picks commits from dependabot PRs and combines it with a few that had to be manually fixed.
🚀 Currently on Dev as v3.2.3h 🚀
- micromatch from 4.0.7 to 4.0.8 
- nanoid from 3.3.7 to 3.3.8 
- path-to-regexp from 1.8.0 to 1.9.0 
- @babel/runtime from 7.24.8 to 7.26.10 
- vite from 5.4.7 to 5.4.12 
- elliptic from 6.5.6 to 6.6.1 
- chore(deps): resolve esbuild to 0.25.0
- see https://github.com/vitejs/vite/issues/19412 for explanation
- chore(deps): resolve dompurify to 3.2.4
- see https://github.com/parallax/jsPDF/issues/3825 for explanation
- chore(deps): resolve canvg to 3.0.11
- see https://github.com/parallax/jsPDF/issues/3834 for explanation
- bumping this to 3.0.11 won't get rid of the …
> chore(deps): resolve outstanding high and moderate security vulnerabilities

- package.json
Closes #2412. All tests passed on dev.
> Upgraded http-proxy-middleware to v2.0.7

- cypress/e2e/tools/olarft.spec.js
- package.json
- src/tools/larft/components/saved-rows/RowID.jsx
- src/tools/larft/components/saved-rows/SavedSection.jsx
- src/tools/larft/components/saved-rows/buildColumns.jsx
- src/tools/larft/components/saved-rows/rft.css
- src/tools/larft/index.css
- yarn.lock
- Updated react-fluid-table from v0.5.1 to v1.4.3 for OLARFT Tool
- Resolved all breaking changes from upgrade
- Updated OLARFT tests
All tests passing on dev. Closes #2244.
> 2244-react-tables

- cypress/e2e/data-publication/DisclosureReports.spec.js
As part of data publication, we needed to update two values in the disclosure report tests once it was on prod.
- update disclosure report tests
1. Do all tests pass? (they do!)
> test(disclosure-reports): update 2024 tests

- cypress/e2e/common-features/navigation.spec.js
In the past, we've had bugs cause pages to silently crash when accessed from the homepage. This adds a test that clicks all the quick links on the homepage and confirms the relevant page headings load.
See [#4951](https://GHE/HMDA-Operations/hmda-devops/issues/4951)
- Adds a new navigation spec
1. `yarn test --spec cypress/e2e/common-features/navigation.spec.js` should pass
> Add homepage navigation tests to detect page crash regressions

- package.json
- yarn.lock
🚀 Currently up on Dev! `v3.2.14` 🚀
- fixes security vulnerabilities by bumping the following deps:
- form-data: >=4.0.4,
- sha.js: >=2.4.12,
- cipher-base: >=1.0.5
1. Do tests still pass on Dev? (they do ✅)
2. How does it look on Dev? (looks good 🎉)
> fix(deps): resolve vulns in formdata, sha, and cipher-base

- src/filing/institutions/Header.jsx
- src/filing/institutions/HeaderOpen.jsx
- src/filing/refileWarning/index.jsx
Updates two banners to include links to LAR tools to make submissions easier.
See [#5029](https://[GHE]/HMDA-Operations/hmda-devops/issues/5029).
- Updates two banners with links to LAR tools.
1. Log into the filing app and check the contents of the blue banner.
2. Upload a malformed LAR and check the contents of the red banner.
Banner at the top of the initial filing screen, slightly different text for annual vs quarterly filers:
| annual filers | quarterly filers |
| ------------- | ---------------- |
| <img width="1996" height="650" alt="image" src="https://github.com/user-attachments/assets/8f5af1d9-a77c-4e21-8327-ebec673067c6" /> | <img width="1996" height="650" alt="image" src="https://github.com/user-attachments/assets/e4b1db78-75af-45cb-9dc2-f00c21355000" /> |
Error banner that …
> Add links to LAR tools in filing banners to assist with file formatting and verification

- public/filesaver.html
When we [added nonces](https://github.com/cfpb/hmda-frontend/pull/2204) to deter XSS vulns, we accidentally broke support for the [third-party library](https://github.com/cfpb/hmda-frontend/pull/851) we use to stream large (> 500MB) LAR blobs. The script loaded by the streaming library throws a CSP error because it doesn't have a nonce. This PR adds one and restores the file download functionality.
We don't actually need the third-party streaming library anymore because modern browsers support up to [2GB of in-memory blobs](https://chromium.googlesource.com/chromium/src/+/HEAD/storage/browser/blob/README.md). I started a [branch](https://github.com/cfpb/hmda-frontend/compare/master...5105-hmda-help-file-download) that removes it and adds tests to catch regressions but I abandoned it when …
> fix(help): add nonce to blob streaming script to fix submission downloads

- .github/workflows/test.yml
- cypress.config.js
- cypress/e2e/filing/Filing.spec.js
- cypress/e2e/filing/Profile.spec.js
- cypress/e2e/hmda-help/institution.spec.js
- cypress/e2e/hmda-help/publication.spec.js
- cypress/e2e/load/LargeFiler.spec.js
- cypress/e2e/tools/RateSpread.spec.js
- cypress/support/e2e.js
- package.json
- yarn.lock
There's a lot of automatic linting fixes, view the diff with [whitespace ignored](https://github.com/cfpb/hmda-frontend/pull/2616/files?diff=split&w=1).
Adds an `@auth-required` tag to cypress tests that require keycloak authentication. Non-auth tests can be run utilizing cypress' [grep package](https://github.com/cypress-io/cypress/tree/develop/npm/grep) by passing `--env grepTags='-@auth-required'` which is saved as a script called `yarn test-non-auth`.
I also created a github workflow to run the tests on pull requests.
Fixes https://github.com/cfpb/hmda-frontend/issues/2604
- Adds a tag to tests that require authentication to run.
- Creates an npm script targeting non-auth tests.
- Adds a github test workflow.
1. The brand new pull request workflow below should pass
- I'm open to other …
> feat: npm script that runs cypress tests that don't require auth
