cfpb/hmda-frontend

src/common/YearSelector.jsx
src/common/constants/years.js
src/documentation/FigLinks.jsx
src/documentation/Home.jsx
src/documentation/Product.jsx
src/documentation/index.js
src/documentation/markdownUtils.js
src/documentation/publications/ModifiedLar.jsx
src/homepage/Home.jsx

- Moves fig docs from homepage into docs and adds extra years to docs

Incorporate changes to homepage/docs

---

src/filing/institutions/Institution.jsx
src/filing/institutions/Progress.jsx
src/filing/institutions/Status.jsx
src/filing/institutions/ViewButton.jsx
src/filing/reducers/submission.js
src/filing/submission/Nav.jsx
src/filing/submission/edits/TableCell.jsx
src/filing/submission/edits/TableRow.jsx
src/filing/submission/parseErrors/index.jsx
src/filing/submission/progressHOC.jsx
src/filing/submission/router.jsx
src/filing/submission/signature/index.jsx

- Incorporates the following PRs:
- cfpb/hmda-platform-ui#1294
- cfpb/hmda-platform-ui#1298
- cfpb/hmda-platform-ui#1299

Incorp ui changes

---

src/app.css
src/filing/institutions/ViewButton.jsx
src/filing/submission/Nav.jsx

- Fixes import errors and csvdownload background color

Button hover fixes

---

src/app.css
src/filing/app.css
src/filing/home/index.jsx
src/filing/modals/Modal.css
src/filing/modals/confirmationModal/index.jsx
src/filing/refileButton/RefileButton.css
src/tools/check-digit/Form.css
src/tools/index.css
src/tools/rate-spread/Form.css

- Fixes some inconsistencies introduced via css splitting

clean up split css

---

nginx/nginx.conf

I've gone through the other front end repos and added the missing `connect-src` entries.
Hopefully closes #21

Add missing connect-src entries

---

src/data-browser/Home.jsx

Closes #36 
Fixes a broken link.

Update Databrowser FAQ link

---

src/filing/refileButton/RefileButton.css

Filing: fix upload file button styles

---

src/filing/submission/container.jsx
src/filing/submission/irs/index.jsx

Filing: update IRS download link per filingPeriod

---

src/common/Alert.css
src/filing/actions/receiveSignature.js
src/filing/actions/receiveSignaturePost.js
src/filing/reducers/signature.js
src/filing/submission/Receipt.jsx
src/filing/submission/ReceiptContainer.jsx

Filing: add email sent message to signature receipt

---

src/App.jsx
src/common/Header.jsx
src/common/appContextHOC.jsx
src/common/configUtils.js
src/common/configUtils.test.js
src/common/constants/config.js
src/common/constants/links.js
src/common/useEnvironmentConfig.jsx
src/documentation/index.js
src/filing/App.jsx
src/filing/home/container.jsx
src/filing/home/index.jsx
src/filing/index.js
src/filing/institutions/container.jsx
src/filing/institutions/index.jsx
src/homepage/index.js

Closes #24 
- Pulls environment variables from Github config file
- Updates Homepage 'Get started...' text based on `config.defaultPeriod`
- Updates Homepage announcement based on `config.announcement`
- Updates Filing's default filing period based on `config.defaultPeriod`
- Updates Filing's and Institution's years available for selection based on `config.filingPeriods`
- Updates Documentation's default year based on `config.defaultPeriod`
1. Manual.  Everything looks good. Would like to get the test suits up and running, probably not in this PR though.

Enable environment variables

---

src/common/Header.jsx
src/data-publication/reports/DynamicDataset.jsx
src/data-publication/reports/SupportingDocs.jsx
src/documentation/tools/DataBrowser.jsx
src/tools/rate-spread/Requirements.jsx

Closes #41 
Closes #42 
Closes #43 
Closes #45 
Closes #46

Frontend fixes

---

src/data-browser/geo/Geography.jsx
src/data-browser/geo/InstitutionSelect.jsx

See https://github.com/cfpb/hmda-data-browser/pull/218

Fix data-browser ie bugs

---

src/documentation/markdown/2019/filing-faq.md
src/documentation/markdown/2020/filing-faq.md

update filing-faq with changes from hmda-documentation

---

src/common/constants/config.json
src/documentation/index.js

closes #64 
- Add new defaultDocsPeriod config variable
- Use variable to route Documentation page

Add defaultDocsPeriod environment variable

---

src/filing/App.jsx
src/filing/index.js

Actually fixes #59 
There was a race condition in App.jsx
Also fixes another bug where env config wasn't being passed into all filing sub-pages.

Keycloak bug

---

src/filing/submission/NavButton.jsx

Edits don't need to be fetched if code is >=14

---

src/common/constants/links.js

hotfix for filing

---

src/App.jsx
src/common/constants/config.json
src/common/constants/links.js
src/filing/home/container.jsx
src/filing/home/index.jsx
src/homepage/index.js

Closes #80 
Closes #82 
- Make 2017 links configurable
- Add link to 2017 filing on Institution sign-in page

Make 2017 filing links configurable

---

src/filing/submission/signature/Signature.css
src/filing/submission/signature/index.jsx

- Adds a LoadingIcon to the signature component, to be shown when signing

add signature loader logic and styles

---

src/filing/actions/updateSignature.js

Automatically retry signing on 405 error

---

src/common/constants/config.json
src/filing/home/container.jsx
src/filing/home/index.jsx
src/homepage/index.js

Closes https://github.com/cfpb/hmda-frontend/issues/102

Remove show2017 config variable and associated logic

---

src/filing/institutions/Header.jsx

Closes https://github.com/cfpb/hmda-frontend/issues/103

Special case 2019 March 2nd filing deadline

---

public/index.html

add precomposed apple touch icon

---

src/filing/utils/checkFileErrors.js

Update error message for questionable text files

---

src/common/Alert.css
src/filing/refileWarning/index.jsx

Update failed file upload message

---

src/documentation/markdown/2018/public-lar-schema.md

Fix as part of https://github.com/cfpb/hmda-platform/issues/3152
1.
-

fix loan_to_value

---

src/tools/lar-formatting/AppIntro.jsx

remove 2017 larft from tools

---

src/data-browser/charts/MapContainer.jsx
src/data-browser/geo/Geography.jsx

fix chartData.json access path and fix data-browser back link

---

src/data-browser/charts/MapContainer.jsx

Closes #153 
Closes #154
- Adds age to the list of data-browser mapping variables
- Fixes mouseleave behavior for more sensible highlighting

add age and fix mouseleave bug

---

src/documentation/markdown/2018/lar-data-fields.md
src/documentation/markdown/2019/lar-data-fields.md
src/documentation/markdown/2020/lar-data-fields.md

https://github.com/cfpb/hmda-platform/issues/3152
1.
-

fix typo lar

---

src/filing/common/Header.jsx

Add doc and ffiec links to Filing page

---

src/tools/check-digit/CSVUpload.jsx
src/tools/rate-spread/CSVUpload.jsx
src/tools/rate-spread/Form.jsx

Correct spelling of "occurred"

---

src/data-publication/reports/fetchMsas.js

Fetch 2017 msaMds from S3 instead of ffiec-api

---

src/filing/actions/fetchInstitution.js
src/filing/common/ErrorWarning.jsx

More informative message when Institution doesn't exist 

---

src/common/constants/config.json

Update banner announcing Monday's maintenance

---

src/common/constants/config.json

Enter Maintenence Mode

---

src/common/constants/config.json

Exit maintenance mode

---

src/common/constants/config.json

Open QF in dev-beta

---

src/common/constants/config.json

Open all Qs in dev-beta

---

src/common/constants/config.json

Announce Feb 6 maintenance

---

src/common/constants/config.json

Closing the beta for required maintenance

wednesday_feb_5_20 maintenance

---

src/common/constants/config.json

NGFW Feb 5 maintenance message

---

src/common/constants/config.json

Closes #215 
- Turn off maintenance mode
- Restore messages to announce Feb 6th maintenance window.

Feb 5 maintenance complete

---

src/common/constants/config.json

Part of #227 
- message on homepage
- message on Filing app

Feb 10 announce maintenance

---

src/common/constants/config.json

Part of #227 
- Set maintenanceMode: true
- Update announcement messages

Feb 10 ENTER maintenance

---

src/common/constants/config.json

Closes #227 
- Restore announcement to 'filing period open'
- Remove maintenance mode

Feb 10 EXIT maintenance

---

Dockerfile

Updated the nginx image to 1.17

update to nginx:1.17-alpine

---

src/common/constants/config.json

Part of #234 
- Set homepage announcement
- Set filing app announcement

Maintenance - Feb 12 - Announce

---

src/common/constants/config.json

Update window to 9-10pm EST
Part of #234

Feb 12 - Announce Maintenance

---

src/common/constants/config.json

Item 2 of #234 
Closes the Filing app
- Set homepage announcement
- Set maintenanceMode: true 
- also sets filing app announcement

Maintenance - Feb 12 - Close Filing

---

src/common/constants/config.json

Closes #234 
Open Filing App
- Restores homepage announcement
- maintenanceMode: false
- removes filing app announcement
- enables login

Maintenance - Feb 12 - Open Filing app

---

src/data-publication/constants/dynamic-dataset.js

Closes https://github.com/cfpb/hmda-frontend/issues/238

Use ultimate datasets for 2017 dynamic national loan-level page

---

src/tools/check-digit/CSVUpload.jsx

Closes #247 
Depends on https://github.com/cfpb/hmda-platform/pull/3487

update check digit csv doc link

---

src/filing/submission/Receipt.jsx
src/filing/submission/irs/index.jsx

Closes #255 
Helps users confused about whether they still need to file if they've submitted in beta

Note beta submission in receipt and remove irs in beta

---

src/common/constants/config.json

Announcement banner for Feb 21, 2020 maintenance time

feb 21 2020 maintenance announcement

---

src/common/constants/config.json

[Maintenance] Feb 21 - Open access

---

src/filing/refileWarning/index.jsx

Closes https://github.com/cfpb/hmda-frontend/issues/265

Add dashes to failed submission note

---

src/filing/constants/dates.js
src/filing/utils/date.js

Adjust filing deadline

---

src/common/constants/config.json

Maintenance - March 9 - Announce

---

src/data-publication/reports/SupportingDocs.jsx

Fix broken links in supporting docs page

---

src/tools/rate-spread/Form.jsx

Closes https://github.com/cfpb/hmda-frontend/issues/285

Prevent submission of non-integer loan terms

---

src/common/constants/config.json

Maintenance - March 9 - Enter Maintenance Mode

---

src/common/constants/config.json

Maintenance - March 9 - Open Filing App

---

src/common/constants/config.json

[Maintenance] March 17 - announce

---

src/data-browser/Home.jsx
src/data-browser/geo/Geography.jsx

Link to db api from homepage and filtering page

---

src/common/constants/config.json

[Maintenance] March 17 - Maintenance Mode: On

---

src/data-publication/reports/Report.jsx

Replace array.from with a direct call to Array.prototype's forEach

---

src/data-publication/index.js

Default mLAR to 2019

---

src/documentation/markdown/2020/quarterly-filing-dates.md

Display QF deadline list correctly

---

kubernetes/beta/hmda-frontend/templates/deployment.yaml
kubernetes/hmda-frontend/templates/deployment.yaml

add k8 deployment settings

---

src/common/constants/config.json

Update mLAR announcement language

---

src/filing/reducers/filings.js

Closes #350 
Avoid accessing pagination details when not present.

Bugfix for accessing missing pagination details

---

src/filing/submission/edits/Table.jsx
src/filing/submission/edits/TableRow.jsx

Closes #365
**Before**
**After**

Suppress duplicate ULI column for V609

---

src/common/Error.jsx

Update Common Error message component

---

cypress/integration/data-publication/DynamicDatasets.spec.js
cypress/integration/data-publication/SnapshotDatasets.spec.js
cypress/support/helpers.js
cypress/support/index.js

Closes #386 
Adds validation of links for Dynamic and Snapshot datasets.

[Cypress] Snapshot and Dynamic Dataset tests

---

src/data-browser/api.js
src/data-browser/geo/Geography.jsx

requestSubset retry after delay

---

src/data-browser/charts/MapContainer.jsx
src/data-browser/charts/MapsGraphs.css

Closes #384 
Closes #385
Instead of the base legend running between 0 - 32, this sets a bias based on the range of values present in each variable/value combination and adjusts the legend labels appropriately.

Adjustable legend

---

src/data-browser/charts/MapContainer.jsx
src/data-browser/charts/MapsGraphs.css

Add zoom controls

---

Dockerfile

[Docker] Upgrade to node:14.2.0-alpine3.11

---

src/data-publication/reports/Disclosure.jsx

[Pub] add IRS location guidance

---

Jenkinsfile

Use tagged helm image and Use correct repo for scans

---

src/documentation/markdown/2017/data-browser-filters.md
src/documentation/tools/DataBrowser.jsx

[Docs] 2017 Data Browser Filters markdown file

---

src/documentation/tools/DataBrowser.jsx

Closes #419 
Will include the addition of a link to the Filter documentation with the release of 2017 DB.

[Docs] Revert link addition for 2017 Data Browser filters

---

src/homepage/index.js

Closes #456 
Shows all homepage links unless deployed on Prod Beta.

[Homepage] Show DB, Tools, etc outside of Prod Beta

---

kubernetes/beta/hmda-frontend/templates/deployment.yaml
kubernetes/hmda-frontend/templates/deployment.yaml

Update security settings in K8 deployment

Remove Priviledges in k8

---

Jenkinsfile

Addresses Internal Github 1798

update internal docker repo

---

src/data-publication/Home.jsx

[DataPub] Link to MLAR 2019 by default

---

src/data-publication/reports/Disclosure.jsx
src/data-publication/reports/MsaMds.jsx

Sorts MSAs by id for disclosure & aggregate reports

---

kubernetes/beta/hmda-frontend/templates/deployment.yaml
kubernetes/hmda-frontend/templates/deployment.yaml

Enable necessary pod privilege

---

cypress/README.md

required for nvm path

---

src/data-publication/reports/Disclosure.jsx

Update doclink year for Disclosure report page

---

src/common/constants/config.json

Fix config for Beta

---

src/filing/institutions/SubmissionHistory.jsx

[Filing] Use submission history sequence number from api to number list items

---

src/common/constants/config.json

Open Filing 2020-Q2

---

src/data-browser/charts/MapContainer.jsx

Fix maps & graphs layer switching in ie

---

src/common/constants/config.json

Closes https://github.com/cfpb/hmda-frontend/issues/531

Sets the defaultPeriod key to 2020 for both dev-beta and prod-beta

---

src/documentation/markdown/2020/lar-formatting.md
src/documentation/tools/LARFT.jsx

[Documentation] Add LARFT Documentation for 2020

---

.travis.yml
package.json

Closes #443 
- Create `.travis.yml`
- Configure `yarn test` to run Cypress

Initial .travis.yml

---

src/tools/rate-spread/index.jsx

Add Rate Spread correction message

---

cypress/docker-runner.sh

script to run cypress and post the results

---

cypress/docker-runner.sh

Cypress docker runner update

---

src/data-browser/charts/MapsGraphs.css

Closes #570 
(assists with #566)

Move legend to bottom right

---

.travis.yml
README.md
package.json
src/filing/utils/keycloak.js

Closes #590 
- Document process of running a Filing locally
- Simplify the commands required to do it

Document local Filing

---

Dockerfile

update hmda-frontend docker image

---

src/filing/institutions/SubmissionHistory.jsx

Include username of Filing submission signer in submission history

---

src/documentation/markdown/2017/identifiers-faq.md
src/documentation/markdown/2018/identifiers-faq.md
src/documentation/markdown/2019/identifiers-faq.md
src/documentation/markdown/2020/identifiers-faq.md
src/documentation/markdown/2021/identifiers-faq.md

Closes #660
- Updates documentation for all available years (2017 - 2021)
- Adds link for Panel schema
- Adds link for Panel field definitions
- Adds link for 2017 FIG Table 1

Identifiers FAQ - add links

---

src/homepage/index.js

[homepage] Update 2017, 2018 FIG links

---

src/generate_data.js

Adds usage info + docs for `generate_data.js`

document generate_data.js script

---

src/common/constants/dev-beta-config.json
src/common/constants/dev-config.json
src/common/constants/prod-beta-config.json
src/common/constants/prod-config.json

Closes #720 
- Open 2020-Q3 in all envs
- Default Documentation year to 2020

[EnvConfig] Add 2020-Q3 and set default docs period to 2020

---

src/filing/institutions/Institutions.css
src/filing/institutions/NameAndId.jsx

Wrap text instead of allowing Details button to shift position

---

cypress/Dockerfile

Update cypress docker to use 5.6.0

---

src/common/constants/prod-beta-config.json

Open 2021 for Prod Beta

---

src/common/constants/dev-beta-config.json
src/data-browser/Home.jsx
src/data-browser/maps/MapContainer.jsx
src/data-browser/maps/filterUtils.jsx
src/homepage/index.js

First checkbox of https://github.com/cfpb/hmda-frontend/issues/763

update maps & graphs default year

---

src/common/constants/dev-config.json

Open 2020 Annual in Dev

---

src/tools/file-format-verification/reducers/index.js
src/tools/lar-formatting/AppIntro.jsx

Update LARFT and FFVT to 2020

---

cypress/integration/hmda-help/publication.spec.js

[Cypress] Update Publication spec to retrigger oldest publication

---

cypress/integration/tools/FFVT.spec.js

Prevent FFVT tests on CI again

---

src/common/constants/links.js

Closes #810 
- Filing link now points to 2020

[Site Nav] Use defaultDocsPeriod for Filing link

---

src/common/constants/configHelpers.js
src/hmda-help/InputSubmit.js
src/hmda-help/search/SubmissionStatus.css
src/hmda-help/search/SubmissionStatus.jsx
src/hmda-help/search/index.js

Closes #711
- Adds a new 'Search Submissions' button
- Fetches Submission info for all Filing years, as configured via the env config.

[Help] Add Oldest/Latest Submission

---

cypress/integration/hmda-help/institution.spec.js
cypress/integration/hmda-help/publication.spec.js

Closes #814 
Fixes currently failing Cypress tests.

[Cypress] Fix button text capitalization for HMDA Help tests

---

src/common/OptionCarousel.css
src/common/OptionCarousel.jsx
src/data-browser/maps/MapContainer.jsx
src/data-browser/maps/MapsGraphs.jsx
src/data-browser/maps/PopularVariableLink.jsx

Addresses comments in #763 
- Update Maps and Graphs description
- Update Step 2 description

Maps and Graphs updates pt. 3

---

src/documentation/markdown/2018/lar-data-fields.md
src/documentation/markdown/2019/lar-data-fields.md
src/documentation/markdown/2020/lar-data-fields.md
src/documentation/markdown/2021/lar-data-fields.md

[Docs] Expand the description for "Derived MSA/MD" for 2018-2021 docs

---

src/documentation/markdown/2017/lar-data-fields.md
src/documentation/markdown/2017/panel-data-fields.md
src/documentation/markdown/2017/ts-data-fields.md
src/documentation/publications/SnapshotDynamic.jsx

[Docs] 2017 LAR, TS, and Panel field names and definitions

---

src/documentation/markdown/2017/panel-data-fields.md
src/documentation/markdown/2017/ts-data-fields.md

[Docs] Fix markdown layout issues for 2017 Panel/TS files

---

src/filing/utils/keycloak.js
src/tools/rate-spread/index.jsx

Closes https://github.com/cfpb/hmda-frontend/issues/852

Update rate-spread error message (and fix keycloak mock function)

---

src/common/constants/prod-beta-config.json
src/common/constants/prod-config.json

[1/4] Maintenance announcement for February 23rd 21

---

src/data-publication/ChangeLog/ChangeLogTable.css
src/data-publication/ChangeLog/ChangeLogTable.jsx
src/data-publication/ChangeLog/change-log-data.json

[ChangeLog] Add latest rate spread message.  Add Links.

---

src/index.js

[Fix] Reorder Polyfill imports

---

src/common/ConfiguredAlert.jsx
src/common/constants/dev-beta-config.json
src/common/constants/dev-config.json
src/common/constants/prod-config.json
src/data-publication/ChangeLog/change-log-data.json
src/homepage/index.js

Add announcement to Homepage
Add update to Publications Change Log

[ModifiedLAR] Announce release of 2020

---

src/common/constants/prod-config.json

```
"announcement": {
"message": "We will be performing scheduled system maintenance on April 22nd from 8pm - 10pm EST. During this time users will be unable to log in to the Filing application or create new accounts.",
"type": "warning",
"heading": "Scheduled Maintenance"
},
```

Restore Maintenance announcement

---

cypress/integration/data-browser/2018.spec.js
cypress/integration/data-browser/2019.spec.js
cypress/integration/hmda-help/institution.spec.js
cypress/integration/hmda-help/publication.spec.js
cypress/integration/tools/RateSpread.spec.js
src/common/useRemoteJSON.jsx
src/hmda-help/search/FilersSelectBox.jsx
src/hmda-help/search/ResultsHeading.js
src/hmda-help/search/Search.css
src/hmda-help/search/index.js

Closes #918
- Search by LEI or Institution name
- Auto-search on selection
- Input sanitization to handle spaces and non-alphanumeric characters that get pasted in
- Additional indicators when user appears to be inputting an LEI vs searching for a name
- Updated Cypress tests

[Help] New Institution search

---

src/common/constants/prod-config.json

Remove link from maintenance banner

Remove link from maintenance banner

---

src/common/constants/prod-config.json

Fix json format error

---

src/hmda-help/publications/constants.js

fix(help): use correct topic for mlar regeneration

---

src/documentation/markdown/2018/data-browser-filters.md
src/documentation/markdown/2018/lar-data-fields.md
src/documentation/markdown/2019/data-browser-filters.md
src/documentation/markdown/2019/lar-data-fields.md
src/documentation/markdown/2020/data-browser-filters.md
src/documentation/markdown/2020/lar-data-fields.md
src/documentation/markdown/2021/data-browser-filters.md
src/documentation/markdown/2021/lar-data-fields.md

docs: add enumeration for ageapplicant

---

src/data-browser/maps/useReportData.jsx

[Maps] Replace "Loans by" with "Applications by"

---

cypress.json
cypress/integration/data-browser/2017.spec.js
cypress/integration/data-browser/2018.spec.js
cypress/integration/data-browser/2019.spec.js
cypress/integration/data-browser/maps.spec.js
cypress/support/helpers.js
src/common/constants/prod-beta-config.json
src/data-browser/maps/MapContainer.jsx
src/data-browser/maps/MapsController.jsx
src/data-browser/maps/MapsGraphs.css
src/data-browser/maps/MapsNavBar.jsx

Closes #978
- Views tested via browser dev tools.
- Opens Maps in Beta, which can be accessed from my mobile device and thus used for live testing of these changes. Data Browser is not presented to users on the Beta homepage.

fix(maps): improve layout for mobile views

---

src/common/constants/prod-beta-config.json
src/common/constants/prod-config.json

Close Maintenance Window

---

src/data-browser/maps/MapContainer.jsx

fix(maps): App crashes when clearing only selected filter

---

nginx/nginx.conf

Closes #1006 
Adds the required policy.

Add Referrer-Policy to nginx config

---

src/documentation/index.css
src/documentation/markdown/2017/panel-data-fields.md
src/documentation/markdown/2018/panel-data-fields.md
src/documentation/markdown/2019/panel-data-fields.md
src/documentation/markdown/2020/panel-data-fields.md
src/documentation/markdown/2021/panel-data-fields.md

[Docs] Correct display of markdown tables

---

src/data-publication/index.css

fix(datapub): Center report tables

---

src/data-publication/ChangeLog/change-log-data.json

task(changelog): National Dataset corrections

---

src/common/constants/prod-beta-config.json

task(beta): Maintenance announcement

---

src/common/constants/prod-beta-config.json

task(beta): post-maintenance notice

---

cypress/integration/data-publication/AggregateReports.spec.js
cypress/integration/data-publication/ChangeLog.spec.js
cypress/integration/data-publication/DisclosureReports.spec.js
cypress/integration/data-publication/DynamicDatasets.spec.js
cypress/integration/data-publication/NationalAggregateReports.spec.js
cypress/integration/data-publication/SnapshotDatasets.spec.js
cypress/support/helpers.js
src/data-browser/datasets/CheckboxContainer.jsx

Closes #1033 
- [changelog] Updates expected counts in the Changelog.spec
- [databrowser] Adds filter id to the displayed label
- [datapublications] Add Data Publications 2020 tests

1033 fix cypress

---

src/common/Beta.jsx

Closes #1050 
Adds language to the Beta header for clearing cache in the event of Filing issues. 
Image `hmda-frontend v1.4.2-preview` is ready for deployment to Beta environment.

task(beta): Update header with cache suggestion

---

nginx/nginx.conf

task(nginx): Extend CSP to include primary ffiec domain

---

src/data-publication/ChangeLog/change-log-data.json
src/data-publication/constants/snapshot-dataset.js

- Add reference table to the Snapshot datasets page for all years
- Add change log entry

(feat) ARID2017 to LEI mapping

---

src/common/Beta.jsx

Remove code change used when testing changes for Beta.

fix: isBeta always returned true

---

src/common/constants/prod-beta-config.json
src/common/constants/prod-config.json

[1/4] Maintenance announcement for August 12 2021

---

src/common/constants/prod-beta-config.json
src/common/constants/prod-config.json

[2/4] Maintenance on announcement for August 12 2021

---

src/common/constants/prod-beta-config.json
src/common/constants/prod-config.json

[3/4] Testing announcement for August 12 2021

---

src/common/constants/prod-beta-config.json
src/common/constants/prod-config.json

- Prevents user access to the Filing application
- Displays notification banner of maintenance activities

1 - Begin extended downtime. Filing app closed for maintenance.

---

src/common/constants/dev-config.json

task(config): Remove dev maint mode

---

src/common/constants/dev-config.json

task(config): Sync announcements with Prod

---

src/common/constants/dev-config.json

Open 2021-Q3 Filing in Dev

---

src/common/constants/prod-beta-config.json

Open 2021-Q3 Filing in Prod Beta

---

src/common/constants/dev-beta-config.json
src/common/constants/prod-config.json

Closes #1106 
Add 2021-Q3 to the config to enable it on the frontend.

task(filing): Open 2021-Q3

---

src/common/constants/prod-beta-config.json
src/common/constants/prod-config.json
src/tools/rate-spread/index.jsx

add rate spread issue announcement

---

src/common/constants/dev-config.json
src/common/constants/prod-beta-config.json
src/common/constants/prod-config.json
src/tools/rate-spread/index.jsx

Closes #1197 
Changes
- Updates homepage banner
- Updates Rate Spread message

Rate spread delay

---

src/documentation/markdown/2018/data-collection-timelines.md
src/documentation/markdown/2019/data-collection-timelines.md
src/documentation/markdown/2020/data-collection-timelines.md
src/documentation/markdown/2021/data-collection-timelines.md

Correct Timeline image name referenced in documentation markdowns

---

src/documentation/markdown/2018/data-collection-timelines.md
src/documentation/markdown/2019/data-collection-timelines.md
src/documentation/markdown/2020/data-collection-timelines.md
src/documentation/markdown/2021/data-collection-timelines.md

[Docs] Collection Timeline - Resubmission ends

---

src/documentation/markdown/2018/filing-faq.md
src/documentation/markdown/2019/filing-faq.md
src/documentation/markdown/2020/filing-faq.md
src/documentation/markdown/2021/filing-faq.md

Closes #1210
Adds a new line before lists so that the they are correctly displayed with bullets and indentation.

Filing FAQ - Fix display of bulleted lists

---

src/data-browser/Home.jsx
src/data-browser/index.js

Closes #1249 
Removes the feature flag checks in the Data Browser code for the Maps feature.  
Note: Removal of the feature flag from the config files will be done as part of #1248.

Maps - Always show

---

src/common/MailingListSignup.jsx

The currently link is inaccessible off-network

Update privacy act link in mailing list signup to www for cf.gov

---

babel.config.js
src/filing/institutions/helpers.js
src/filing/institutions/helpers.spec.js
src/filing/institutions/index.jsx

Closes #1279 
Redirects non-Quarterly users to the next available Annual filing period.

Filing - Redirect non-Quarterly users to next annual

---

src/common/constants/dev-config.json
src/common/constants/prod-beta-config.json
src/common/constants/prod-config.json
src/tools/rate-spread/index.jsx

[WIP] config for notification

---

src/common/constants/dev-config.json
src/common/constants/prod-beta-config.json
src/common/constants/prod-config.json
src/tools/rate-spread/index.jsx

rate spread issue resolved message

---

src/data-publication/ChangeLog/constants.js

[ChangeLog] Add HMDA Filing as a product

---

src/data-publication/ChangeLog/change-log-data.json

[ChangeLog] Add updates about Filing fixes

---

src/common/constants/prod-beta-config.json

[Beta] Add banner for preview of new LARFT

---

cypress/integration/data-publication/ModifiedLAR.spec.js
src/common/constants/dev-config.json
src/data-publication/reports/SupportingDocs.jsx

Part 1 of #1377 
- Add Cypress test for 2021
- Adds documentation for 2021
- Enabled 2021 in Dev environments

Modified LAR 2021 - Part 1

---

src/common/constants/dev-config.json
src/common/constants/prod-beta-config.json
src/common/constants/prod-config.json

Adjust configuration for 2021 MLAR release

2021 mlar release

---

src/hmda-help/publications/constants.js

Closes #1388 
Updates the Kafka Topic used for Modified LAR regeneration.

[Help] Update MLAR regeneration topic

---

cypress/Dockerfile

Update Dockerfile to remove private keys

---

src/documentation/FAQs.jsx
src/documentation/markdown/2018/data-browser-faq.md
src/documentation/markdown/2018/static-dataset-faq.md
src/documentation/markdown/2019/data-browser-faq.md
src/documentation/markdown/2019/static-dataset-faq.md
src/documentation/markdown/2020/data-browser-faq.md
src/documentation/markdown/2020/static-dataset-faq.md
src/documentation/markdown/2021/data-browser-faq.md
src/documentation/markdown/2021/static-dataset-faq.md
src/documentation/markdown/2022/data-browser-faq.md
src/documentation/markdown/2022/static-dataset-faq.md
src/documentation/publications/SnapshotDynamic.jsx

Documentation for new static datasets

---

src/common/constants/dev-config.json
src/common/constants/prod-beta-config.json
src/common/constants/prod-config.json
src/data-publication/ChangeLog/change-log-data.json

[Go Live] 2021 Data Pub configurations

---

src/common/constants/dev-config.json
src/common/constants/prod-beta-config.json
src/common/constants/prod-config.json

Closes #1468 
Delete outdate homepage banner announcements

[Config] Clean up Homepage announcements

---

src/data-publication/ChangeLog/change-log-data.json
src/tools/rate-spread/index.jsx

| Desc | SS |
|---|---|
|Adds note on Rate Spread page|<img width="990" alt="rate-spread-page" src="https://user-images.githubusercontent.com/2592907/180570412-9867da2c-7a4b-4991-b7c0-b35631da3bfb.png">|
|Adds entry to Data Pub - Change Log|<img width="1054" alt="change-log-entry" src="https://user-images.githubusercontent.com/2592907/180570461-2d73231d-ce1b-4bb7-a722-a21acf40969a.png">|

Rate spread update jul 21

---

src/common/constants/prod-beta-config.json
src/common/constants/prod-config.json

[1/3] Maintenance Announcement for August 2 2022

---

src/homepage/index.js

Closes #1489 
Closes #1491 
- Corrects endpoint of homepage link to the CFPB Regulatory Implementation website

[Homepage] Fix link to CFPB Regulatory Implementation website

---

src/updates-notes/change-log-data.json

[ChangeLog] Announce Graphs release

---

src/data-browser/graphs/quarterly/useManageGraphSelection.jsx
src/data-publication/Home.jsx
src/homepage/ForDataUsers/DataBrowser.jsx
src/updates-notes/constants.js

[ChangeLog] Fetch JSON from updated github location

---

src/documentation/markdown/2019/data-browser-graphs-faq.md
src/documentation/markdown/2020/data-browser-graphs-faq.md
src/documentation/markdown/2021/data-browser-graphs-faq.md
src/documentation/markdown/2022/data-browser-graphs-faq.md

[Docs] Graphs FAQ - Update content

---

src/common/constants/dev-config.json
src/common/constants/prod-beta-config.json
src/common/constants/prod-config.json

Closes #1525  
Adds this banner to the Prod and ProdBeta environments.

[Homepage] Graphs release banner

---

src/updates-notes/change-log-data.json

Closes #1517 
- Add Updates and Notes entry
- Do we want a banner?

[Updates and Notes] Release of 2023 FIG

---

src/homepage/ExpandableCard.jsx
src/homepage/ForFilers/Filing.jsx

[Homepage] Open Filing app in new tab to avoid dual page headers

---

cypress/integration/tools/FFVT.spec.js

[Cypress] Update FFTV test to match new language

---

src/documentation/markdown/2018/lar-data-fields.md
src/documentation/markdown/2019/lar-data-fields.md
src/documentation/markdown/2020/lar-data-fields.md
src/documentation/markdown/2021/lar-data-fields.md
src/documentation/markdown/2022/lar-data-fields.md
src/documentation/markdown/2023/lar-data-fields.md

Closes #1563 
Adds the missing Code 7 to all AUS 1-5 fields
<br/>

[Docs] LAR Data Fields - Add Code 7 to aus-* fields

---

src/documentation/markdown/2018/data-browser-faq.md
src/documentation/markdown/2019/data-browser-faq.md
src/documentation/markdown/2020/data-browser-faq.md
src/documentation/markdown/2021/data-browser-faq.md
src/documentation/markdown/2022/data-browser-faq.md
src/documentation/markdown/2023/data-browser-faq.md

Closes #1568
Adds a question mark to the end of "What is a CSV" header for all years.

[Data Publication] Updated HMDA - Data Browser FAQ Header for all years.

---

src/common/constants/dev-config.json
src/common/constants/prod-beta-config.json
src/common/constants/prod-config.json
src/updates-notes/change-log-data.json

Closes #1570 
Draft: Pending the backend rollout.

[Data Browser] Quarterly Graphs - Announce update to include 2022-Q2 data

---

src/updates-notes/change-log-data.json

[ChangeLog] Correction to Graphs data for 2022-Q1

---

src/data-publication/reports/Results.jsx

[ModifiedLAR] Construct filename to include LEI and appropriate labeling

---

src/documentation/markdown/2018/lar-data-fields.md
src/documentation/markdown/2019/lar-data-fields.md
src/documentation/markdown/2020/lar-data-fields.md
src/documentation/markdown/2021/lar-data-fields.md
src/documentation/markdown/2022/lar-data-fields.md
src/documentation/markdown/2023/lar-data-fields.md

[Documentation] Update lar-data-fields markdown file

---

cypress/integration/data-publication/ModifiedLAR.spec.js

[Cypress] Update Modified LAR test for proxied URLs

---

src/data-browser/graphs/highchartsConfig.js

[Graphs] Y-Axis Labels displays M or K on respective values

---

src/data-browser/graphs/SectionSelector.jsx
src/data-browser/graphs/quarterly/QuarterlyFilersTable.jsx
src/data-browser/graphs/quarterly/SectionGraphs.jsx
src/data-browser/graphs/quarterly/useFetchGraphList.jsx
src/data-browser/graphs/quarterly/useFetchSingleGraphs.jsx
src/data-browser/graphs/slice/api/graphs.js
src/data-browser/graphs/slice/api/institutions.js
src/data-browser/graphs/slice/api/status.js
src/data-browser/graphs/slice/graphsSlice.js
src/data-browser/graphs/slice/institutionsSlice.js
src/data-browser/store/index.js

Rtk query update

---

src/common/constants/configHelpers.js
src/common/constants/configHelpers.spec.js

Closes #1611 
yarn jest src/**/configHelpers*

[config] Always allow HMDA Help access to *next* year in Beta environments

---

src/common/OptionCarousel.css
src/homepage/AnnouncementBanner.jsx
src/homepage/ColumnLayout.css

Closes #1616 
|Before|After|
|---|---|
|![hmda-homepage-before](https://user-images.githubusercontent.com/2592907/196011137-e5c946e8-5f92-4969-ac11-56508d7ffa99.gif)|![hmda-homepage-after](https://user-images.githubusercontent.com/2592907/196011160-2b7b1b54-a6bf-421f-b017-d971226ee5b8.gif)|

[Homepage] Improve layout responsiveness for small devices

---

src/documentation/markdown/2019/data-browser-graphs-faq.md
src/documentation/markdown/2020/data-browser-graphs-faq.md
src/documentation/markdown/2021/data-browser-graphs-faq.md
src/documentation/markdown/2022/data-browser-graphs-faq.md
src/documentation/markdown/2023/data-browser-graphs-faq.md

Closes #1532 
New FAQ section discussing the different loan types has been added to the Graphs FAQ page.

[Graphs] Clarify different loans types

---

cypress/integration/hmda-help/institution.spec.js
scripts/lar/constants.mjs
scripts/lar/generate_lar_file.mjs
scripts/lar/lar_helpers.mjs

Closes #1639 
- Updates login method for one of the Institution tests
- Reverts LAR generation script to match Cypress' max upload size

1639 cypress issues

---

src/common/ExternalLink.jsx
src/common/S3Integrations.jsx
src/data-publication/reports/SupportingDocs.css
src/data-publication/reports/SupportingDocs.jsx
src/documentation/publications/ModifiedLar.jsx
src/documentation/publications/SnapshotDynamic.jsx
src/documentation/tools/DataBrowser.jsx
src/documentation/tools/RateSpread.jsx
src/filing/submission/irs/index.jsx

[External Links] Updated links to use ExternalLink or S3DockLink components

---

src/common/constants/dev-config.json
src/common/constants/prod-beta-config.json
src/common/constants/prod-config.json

[Filing Announcement] Filing banner for end of 2019 data collection

---

src/common/constants/dev-config.json
src/common/constants/prod-beta-config.json
src/common/constants/prod-config.json
src/homepage/AnnouncementBanner.jsx

Closes #1610
|Banner|Expires On|Age at Expiration
|---|---|---|
|<img width="902" alt="Screen Shot 2022-11-09 at 5 12 25 PM" src="https://user-images.githubusercontent.com/2592907/200969032-804fae5c-f7a0-4538-8df0-63b9973b1721.png">| Dec. 3rd, 2022| 3 Months old|
|<img width="904" alt="Screen Shot 2022-11-09 at 5 12 12 PM" src="https://user-images.githubusercontent.com/2592907/200969062-7b43254d-4d26-471e-ab60-4c6ee2a3a988.png">|Dec. 31st, 2022|8+ months old|

Automates announcement banner removal

---

src/common/constants/prod-config.json

maintenance 1

---

src/common/constants/prod-config.json

s3 access issue banner

---

src/common/constants/prod-config.json

s3 access resolved banner

---

src/common/constants/prod-config.json

s3 issue resolved banner level info

---

src/tools/rate-spread/AppIntro.jsx

[Rate Spread] Reword Freddie Mac data source description

---

kubernetes/beta/hmda-frontend/templates/service.yaml
kubernetes/hmda-frontend/templates/service.yaml

Update ambassador service.yaml

---

src/common/TableOfContents.css

[TOC] Scope styles

---

cypress/integration/data-browser/maps.spec.js

Closes #1683
Will probably have merge conflicts with the Cypress upgrade branch, so will address that when we come to it.

[Cypress] Delete Beta banner in Maps tests to allow proper scrolling

---

nginx/nginx.conf

[nginx] Add Permissions-Policy header

---

src/common/constants/dev-config.json
src/common/constants/prod-beta-config.json
src/common/constants/prod-config.json

[Filing] Remove 2019 End of Collection banner from Filing app

---

src/common/constants/dev-config.json
src/common/constants/prod-beta-config.json
src/common/constants/prod-config.json

Closes #1698 
- Removes `File Access Restored` announcement
- Removes other expired announcements
Ready to merge after approval.

[Banner] Remove outdated announcements

---

src/common/Beta.css
src/common/Beta.jsx
src/common/OptionCarousel.css

Closes #1702 
- Differentiate between Beta banner and Announcement banners
- Fix Announcement banner overflow for longer messages
- Improve cover of Announcement background on small screens
- Reduce empty space for Announcements with shorter messages

[Homepage] Improve alert/banner design

---

src/common/constants/dev-config.json
src/common/constants/prod-beta-config.json
src/common/constants/prod-config.json
src/updates-notes/change-log-data.json

[Data Browser] Quarterly Graphs - Announce update to include 2022-Q3 data

---

src/filing/actions/fetchUpload.js

Closes #1722 
|Before|After|
|--|--|
|<img width="991" alt="Screen Shot 2023-02-13 at 3 54 28 PM" src="https://user-images.githubusercontent.com/2592907/218592946-3e2f027d-aa0f-4ad3-ae5d-1382b4063f94.png">|<img width="959" alt="upload-more-detail" src="https://user-images.githubusercontent.com/2592907/217670736-7ed4acc3-f295-4538-b260-bbed9577a1c2.png">|
- Extracts and displays error message from the response's JSON payload in order to provide more detailed user feedback.
1. Upload a LAR file that has a line with 2049+ characters
2. Observe that the UI error message shows the message from the API's JSON response of `Invalid file format` instead of simply the Response object's statusText of `Bad Request`.

[Filing] Upload: Display JSON error message in UI to provide more detail

---

src/updates-notes/change-log-data.json

[ChangeLog] Announce fix for IRS Report access

---

src/common/constants/prod-beta-config.json
src/common/constants/prod-config.json

[Maintenance] Announce March 7 maintenance

---

src/common/constants/prod-beta-config.json
src/common/constants/prod-config.json

[Maintenance] Begin March 7 maintenance

---

src/common/YearSelector.css
src/common/constants/dev-config.json
src/common/constants/prod-beta-config.json
src/common/constants/prod-config.json
src/data-publication/Home.jsx
src/data-publication/reports/CombinedMLAR.jsx
src/data-publication/reports/ModifiedLar.css
src/data-publication/reports/ModifiedLar.jsx
src/data-publication/reports/SearchList.css
src/data-publication/reports/SearchList.jsx
src/updates-notes/change-log-data.json

- Homepage announcement
- Add `2022` option to MLAR page

Combined MLAR release

---

src/common/constants/prod-config.json

Combined MLAR - Release v2

---

src/updates-notes/change-log-data.json

Change "blog post" to "press release"

Combined MLAR - Release - Changelog v2

---

src/documentation/tools/RateSpread.jsx
src/tools/index.js
src/tools/rate-spread/AppIntro.jsx
src/tools/rate-spread/Methodology.jsx
src/tools/rate-spread/Methodology2.jsx
src/tools/rate-spread/Methodology_Alt.jsx

- Updated Rate Spread Methodology
- Added Methodology-Alt page for previous Methodology
- Updated Rate Spread Documentation links
- Updated Rate Spread landing page text
1. Cypress Rate Spread tests passed

3688 rate calc update

---

src/common/constants/dev-config.json
src/common/constants/prod-config.json
src/updates-notes/change-log-data.json

PR is designed to display rate spread calculator announcement banner updates to prod and dev and add a new note in the update notes section.

3688 rate spread announcement

---

src/common/Beta.css
src/common/WarningBanner.jsx
src/documentation/Home.jsx

[Documentation] Banner announcement about documentation overhaul

---

src/documentation/markdown/2023/online-lar-formatting.md
src/documentation/markdownUtils.js

Found a few files that had hard coded values for the olarft branch. This PR fixes those issues.

[olarft] Fix harded olarft values

---

src/common/constants/dev-config.json
src/common/constants/prod-config.json
src/updates-notes/change-log-data.json

Adds olarft announcement banner to prod and dev config.
Removes some out of date banners.

[Config] olarft announcement banner addition

---

src/common/constants/prod-beta-config.json

Closes #1791 
Online OLARFT tool has been released to production. PR created to remove the banner from the beta site.

[Banner] Remove olarft banner from beta site

---

src/data-browser/datasets/DocLink.jsx

PR fixes a bug that was found inside the DocLink component causing the Data browser table to not load.

Fixes a bug inside DocLink component.

---

src/common/constants/dev-config.json
src/common/constants/prod-config.json
src/updates-notes/change-log-data.json

[Banner, Changelog] Docusaurus announcement banner and change log updates

---

src/common/TableOfContents.jsx
src/documentation/markdown/2023/data-browser-graphs-faq.md

Re-adding file for graphs markdown FAQ. This fixes an issue on the graphs FAQ tab where the markdown parser is looking for the graphs markdown file.

[Markdown, Graphs] Re-adding graphs markdown file

---

cypress/e2e/data-browser/dataset-filtering.spec.js

[Cypress] Resolve failing dataset filtering spec file

---

src/common/constants/prod-beta-config.json
src/common/constants/prod-config.json

Maintenance Banner of 6/28/2023

[1/3] Maintenance Announcement for June 28, 2023

---

src/common/constants/prod-beta-config.json
src/common/constants/prod-config.json

[2/3] Maintenance Begins: June 28, 2023

---

cypress/e2e/data-browser/maps.spec.js
cypress/support/e2e.js

Closes #1832 
Fixed failing Maps test for 2022 / 2021.

[Cypress] Handles _384 error 

---

src/common/Header.jsx
src/common/constants/dev-config.json
src/common/constants/prod-config.json
src/homepage/ForFilers/Filing.jsx
src/homepage/ForFilers/FilingDocs.jsx
src/homepage/index.js

Generates a banner that tells folks about the HMDA Online FIG prototype and adds a new link on beta site to allow people to directly go to the the HMDA FIG.

HMDA FIG Prototype Banner

---

cypress/README.md

Added terminal command to run Check Digit locally so you can then generate the MAX.txt file.

Updated Readme: Check Digit

---

src/filing/App.jsx

[BETA] Removes banner from filing homepage

---

src/common/ReleaseVersion.jsx

HMDA build version links to Github releases

---

nginx/nginx.conf

Fixed GTM Errors in DEV. Closes #1861.

Updated CSP to include GTM MouseFlow + DoubleClick

---

src/common/constants/dev-config.json
src/common/constants/prod-beta-config.json
src/common/constants/prod-config.json
src/common/constants/years.js
src/updates-notes/change-log-data.json

Files have been tested in DEV. Banner / Update won't show up  until merged.

Added 2024 FIG to Banner/Homepage/ChangeLog

---

src/filing/submission/irs/index.jsx

Updates IRS for submitted quarterly filings

---

src/common/constants/prod-config.json
src/updates-notes/change-log-data.json

Displays a banner to users letting them know graphs has been updated with 2023-Q2 data!
Additionally updates the change log to include the update and a new entry was added for 2023-Q1.

Graphs 2023-Q2 Release

---

src/common/constants/prod-beta-config.json

Banner to let users know there is an issue with 2023 filing on prod beta.

Banner for prod beta 2023 filing issue

---

src/common/constants/prod-beta-config.json

2023 Annual filing issue has been fixed. PR is to remove the banner from prod beta.

Remove 2023 filing issue banner

---

src/updates-notes/change-log-data.json

Updated json to include 2024 FIG Update.

Added 2024 FIG Update to change log.

---

src/data-publication/reports/Aggregate.jsx
src/data-publication/reports/Disclosure.jsx

Update broken links found on Aggregate and Disclosure report pages

---

src/filing/institutions/ViewButton.jsx
src/filing/submission/Nav.jsx

Filing navigation edge case

---

src/homepage/ForFilers/FilerInfo.jsx
src/homepage/ForFilers/FilingGuides.jsx

[Homepage] Reorder "Info for Filers" sections

---

cypress/e2e/filing/Filing.spec.js

Resolves failing tests in the filing section.

[Cypress] Fixes failing profile page tests

---

src/homepage/ForDataUsers/DataDocs.jsx

Pairs with our Docusaurus documentation updates. Docusaurus [PR here](https://github.com/cfpb/hmda-combined-documentation/pull/35).
Closes #2008

Points links to updated Docusaurus documentation

---

src/data-browser/Home.jsx
src/data-browser/maps/MapsGraphs.jsx

Additional PR to close out #2008. A few links were missed when updating them to the new Docusaurus links.

[Docusaurus Links] Updates additional links

---

src/common/constants/prod-config.json
src/updates-notes/change-log-data.json

Announces MFA/Profile page and updates change-log to include the announcement.

Announces MFA

---

cypress/e2e/data-browser/graphs.spec.js
src/data-browser/graphs/graphs.css
src/data-browser/graphs/highchartsConfig.js
src/data-browser/graphs/quarterly/SectionGraphs.jsx

Added Loan Purpose Dropdown to Quarterly Graphs:

Added Loan Purpose Dropdown to Quarterly Graphs

---

src/common/constants/prod-config.json
src/updates-notes/change-log-data.json

Adds the Announcement Banner + Change Log for the 2023-Q3 Quarterly Graphs update

QuarterlyGraphs - Announcement Banner + Change Log

---

README.md

removing travis instructions from readme

---

src/common/Header.jsx
src/common/uswds/js/uswds-init.min.js

USWDS navbar is now available after just 1 second.

Reorders uswds loading scripts and reduced timeout

---

src/common/constants/dev-config.json
src/common/constants/prod-config.json

[Announcement] Modified LAR Data Release Banner

---

cypress/e2e/data-publication/CombinedMLAR.spec.js
cypress/e2e/data-publication/ModifiedLAR.spec.js

Closes #2133 
Ran the updated tests against production and they all passed! ✅

[Cypress] Modified LAR & Combined MLAR 2023 test coverage support

---

src/common/LargeFileWarning.jsx
src/data-browser/datasets/ActionsWarningsErrors.jsx
src/data-browser/datasets/Geography.jsx

[Data Browser] Expand Nationwide Large File Warning

---

src/common/constants/links.js

Updated Nav to point to 2024FIG

---

src/filing/institutions/container.jsx
src/filing/profile/CompleteProfile.jsx
vite.config.js

[Filing Profile Page] Adjust profile page due to Keycloak upgrade

---

cypress/e2e/filing/Keycloak.spec.js

[Cypress] Update Keycloak test

---

cypress/e2e/data-browser/graphs.spec.js

[Cypress] un-skip Graph test

---

README.md

#2109 
Introduces new section on how to `Add GIFs` to the README.

[README] Adding GIFs

---

README.md

Updates the code coverage badge found in the README from 85% to 90%.

[README] Update Code Coverage Badge

---

src/hmda-help/institution/index.jsx
src/hmda-help/search/fetchInstitution.js

[HMDA Help] Refetch Selected Year when editing an Institution

---

nginx/nginx.conf

Closes #3663 on DevOps. All tests passed on dev.

Remove XSS from nginx.conf

---

index.html
nginx/nginx.conf

Closes #2192. Tests passing on dev.

Updated nginx csp and google analytics script

---

src/common/Header.jsx

Fixed Mobile Nav Height

---

src/common/constants/prod-config.json
src/updates-notes/change-log-data.json

Opens 2023 Data publication within the UI.

Data Publication Configs for 2023

---

cypress/e2e/updates-notes/ChangeLog.spec.js

[Cypress] Update Change Log test to support 2023 Data Publication entry

---

kubernetes/beta/hmda-frontend/values.yaml
kubernetes/hmda-frontend/values.yaml

Updates the values.yaml files for Beta and Production

---

src/common/constants/dev-config.json
src/common/constants/prod-config.json
src/updates-notes/change-log-data.json

Closes #2247 & #2248
🔴 MLAR Release
🟢 2024-Q1 Graphs release
🟢 MFA (Multi Factor Authentication) language has been changed
🟢 2024-Q1 Graphs release

Banner cleanup + change log update

---

src/common/constants/dev-config.json
src/common/constants/prod-config.json
src/updates-notes/change-log-data.json

Displays a banner announcing 2025 Online FIG & Supplemental Guide for Quarterly Filers.
Add a new entry in the change-log linking to the 2025 Online FIG & 2025 Supplemental Guide for Quarterly Filers.

[Banner + Change Log] 2025 Online FIG & Supplemental Guide for Quarterly Filers

---

src/updates-notes/change-log-data.json

The pull request will be merged in after the [Docusaurus PR](https://github.com/cfpb/hmda-combined-documentation/pull/71) has been merged and deployed to production.
Closes #2299

[Change Log] 2024 Online FIG Update

---

src/app.css
src/data-publication/index.css
src/data-publication/reports/DynamicDataset.css
src/data-publication/reports/ModifiedLar.css
src/data-publication/reports/snapshot/Snapshot.css
src/filing/home/Home.css
src/tools/file-format-verification/FFVT.css

Closes 2303. Updated CSS to make h1 size, spacing, and color consistent across all pages.

[Frontend] Consistent Page Headings

---

cypress/Dockerfile
cypress/docker-runner.sh

Currently running and passing against Prod. Closes #2355

Moved Cypress e2e fixtures from s3 to docker image

---

src/common/constants/prod-beta-config.json
src/common/constants/prod-config.json

Temp banners for Dec20 scheduled maintenance

Temp banner for dec20

---

src/common/constants/prod-config.json

Updated filing announcment

---

cypress/docker-runner.sh

Updated docker-runner.sh to log cypress

Updated Cypress logging

---

cypress/e2e/filing/Keycloak.spec.js

Updated keycloak test for cypress

---

src/common/constants/dev-config.json
src/common/constants/prod-config.json

Removes the 2024 Q1 Quarterly Graphs Announcement Banner

---

src/common/constants/prod-beta-config.json

Remove Maintenance Mode & Announcements from Prod-Beta

---

src/common/constants/dev-config.json

Added maintenance banner for login.gov outage to dev.

---

cypress/e2e/filing/Filing.spec.js

Fixed 2025-Q1 filing test. Closes #2462. All CronJob tests are passing against Prod.

Fixed 2025-Q1 filing test

---

src/common/constants/prod-beta-config.json

Closes 2493. Updates prod-beta-config.json announcement to blank array.

prod-beta-config.json Update

---

src/updates-notes/change-log-data.json

- add changelog notice for updated data due to Conforming Loan Limit issue

docs(changelog): add note about conforming loan limit fix
